### ISSUE TITLE
couchjs fails to run on High Sierra from binary package

### ISSUE THREAD

**Issue by thgautier92** [apache/couchdb#979] opened 2017-11-10 16:37 UTC
When I execute the installation verify test, the view is never created and a error message is displayed.

## Expected Behavior
The view must be created
## Current Behavior
The view is never created and a error message is displayed : 

> Error: undefined

## Steps to Reproduce (for bugs)
1. Install Apache Couchdb.app from the web site
2. Run the application
3. Setup a single node, with user and password, and 127.0.0.1 as host
4. Verify the installation 

## Context
I want to migrate the 1.6.x installation to the newest version 2.1.1.
The installation is most operational, but only views on my existing databases doesn't work.
 So i tried to verify if the installation was correct. 

## Your Environment
* Version used: 2.1.1
* Browser Name and version: Chrome 62
* Operating System and version (desktop or mobile): MAC OS SIERRA 10.13
* Log file:
[CouchDB2.log](https://github.com/apache/couchdb/files/1462038/CouchDB2.log)

**Comment by wohali** [comment] 2017-11-10 17:47
`{exit_status,134}` in the logfile for the `couchjs` process says that something isn't quite right with your installation and setup. I don't have a Mac with 10.13 available for testing so I can't help any further, sorry.

**Comment by lyudmil** [comment] 2017-11-15 14:10
@wohali, I think this issue is not as specific to @thgautier92's setup as we might hope. I can confirm I have the same problem after applying the latest update of MacOS (10.13.1). I'm able to reproduce the problem without step 3 – just installing the binary application and verifying the install fails:

There many crash reports in my system log related to CouchDB, all pretty much one of two types. One is:

```
Process:               couchjs [11507]
Path:                  /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/couchjs
Identifier:            couchjs
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        erl_child_setup [752]
Responsible:           couchjs [11507]
User ID:               501

Date/Time:             2017-11-15 15:58:26.219 +0200
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:        D39DCAE6-734C-498E-F796-1FECDA8DD5CF


Time Awake Since Boot: 950 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
...
```

And here's the other:

```
Process:               beam.smp [690]
Path:                  /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/erlang/erts-6.1/bin/beam.smp
Identifier:            beam.smp
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Apache CouchDB [682]
Responsible:           beam.smp [690]
User ID:               501

Date/Time:             2017-11-14 17:06:00.744 +0200
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:        D39DCAE6-734C-498E-F796-1FECDA8DD5CF


Time Awake Since Boot: 1400 seconds

System Integrity Protection: enabled

Crashed Thread:        10

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000100000074
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
...
```

I'm available and willing to try things out on my Mac to help resolve this. Let me know how I might be useful.

**Comment by lyudmil** [comment] 2017-11-15 16:09
I updated a number of other components on my system (including Erlang), and I no longer get the crash reports I described previously. I do see this when I try to run the install verification, though:

```
default	18:04:59.473126 +0200	kernel	Process[11374] crashed: couchjs. Too many corpses being created.
default	18:04:59.484397 +0200	taskgated	MacOS error: -67062
default	18:04:59.490932 +0200	kernel	Process[11375] crashed: couchjs. Too many corpses being created.
default	18:04:59.503040 +0200	taskgated	MacOS error: -67062
default	18:04:59.509553 +0200	kernel	Process[11376] crashed: couchjs. Too many corpses being created.
default	18:04:59.521725 +0200	taskgated	MacOS error: -67062
default	18:04:59.528253 +0200	kernel	Process[11377] crashed: couchjs. Too many corpses being created.
default	18:04:59.542521 +0200	taskgated	MacOS error: -67062
default	18:04:59.553778 +0200	kernel	Process[11378] crashed: couchjs. Too many corpses being created.
default	18:04:59.570313 +0200	taskgated	MacOS error: -67062
```

The error coming from `taskgated` is a security exception. It looks like macOS is blocking `couchjs` from running on security grounds.

**Comment by wohali** [comment] 2017-11-15 17:05
Again I can't help diagnose as I don't have a Mac handy. @janl will need to follow up with you as he is responsible for the macOS package.

**Comment by sinitean** [comment] 2017-11-16 02:03
I'm seeing a similar issue on OSX 10.13.1. It happens with any view or if you decide to replicate anything that has a design doc attached. 
The couchdb.log entry is:
[info] 2017-11-15T23:05:22.685021Z couchdb@localhost <0.218.0> -------- couch_proc_manager <0.24207.0> died normal
[error] 2017-11-15T23:05:22.685029Z couchdb@localhost <0.9320.0> c5d0527261 OS Process Error <0.24207.0> :: {os_process_error,{exit_status,134}}

The moment I try to create a view the message above floods the log and memory consumption on my mac maxes out (I have 40gig of memory). I end up killing couch before it kills my machine. 

I see the upgrade nodes for 2.1.1 and wonder if it is related to #914 and #916. 
https://github.com/apache/couchdb/pull/916
https://github.com/apache/couchdb/pull/914

The problems are not limited to my Mac install.
I see also similar errors on ubuntu 16.04 on 2 separate servers.
Using curl, trying a replication of a db ("mydb") that contains views get me: 
{"error":"error","reason":"{http_request_failed,\"GET\",\n    \"https://admin:*****@127.0.0.1:5984/mydb/\",\n    {error,{error,{conn_failed,{error,{tls_alert,\"record overflow\"}}}}}}"}

If I 'm trying to create or delete a db via curl:
 curl -X PUT http://admin:****@127.0.0.1:5984/testdb
 or 
curl -X DELETE http://admin:****@127.0.0.1:5984/testdb
 I get the following error:
{"error":"error","reason":"internal_server_error"}
Interestingly, the db is created / deleted as it can be seen on Fauxton or by doing a curl get _all_dbs.
This works also with the verifydb test. If you run the verification step you get an error and then in Fauxton you see it greyed out with "database could not be loaded". But you can remove (and re-add) it via curl despite getting the error.

**Comment by TomArbuckle** [comment] 2017-11-17 14:38
@wohali 

Concerning the missing library problem, continuing on from the previous report by @lyudmil (quoting previous text)

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
```

I see the error in the macOS console User reports (macOS 10.12.6) continues as

```
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/nspr/4.17/lib/libnspr4.dylib
  Referenced from: /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/*/libplds4.dylib
  Reason: image not found
```

In other words, the Macintosh application binary has a dependency on an external library which is not distributed as part of the download and may not be present on users' machines.

It's a packaging issue.

HTH.

**Comment by martinleopold** [comment] 2017-11-17 23:32
I can confirm this, @TomArbuckle. Since `/usr/local/Cellar` is the default location for homebrew packages, I tried doing a `brew install nspr`. Now I can sucessfully verify my CouchDB 2.1.1 installation on macOS 10.13.1.

Before:
<img width="1124" alt="screen shot 2017-11-18 at 00 05 55" src="https://user-images.githubusercontent.com/1692826/32973464-ed05faa6-cbf7-11e7-8bc4-13266c057b30.png">

After:
<img width="848" alt="screen shot 2017-11-18 at 00 28 32" src="https://user-images.githubusercontent.com/1692826/32973448-d482cefa-cbf7-11e7-80b8-6645eb7c449a.png">

**Comment by sinitean** [comment] 2017-11-18 01:47
I’m also on OS X 10.13.1. I checked under the os x console my user reports logs and found the same termination reason in the couchjs crash logs. I installed nspr via brew and the install is working normally again. The verification succeeds, views creation works and replication works. I’m a happy camper again :-)

**Comment by dantelepoole** [comment] 2017-11-18 20:38
Installing nspr with brew fixed the same problem for me as well.

**Comment by charliev** [comment] 2017-11-23 21:38
Hitting the same wall here, suspecting a js runtime problem (had quite a few of those thanks to nvm) I tried
`
charlie:couchdbx-core charlie$ ./bin/couchjs ./share/server/main.js
dyld: Library not loaded: /usr/local/Cellar/nspr/4.17/lib/libnspr4.dylib
  Referenced from: /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/libplds4.dylib
  Reason: image not found
Abort trap: 6
`
ergo:
1. yes, it is a packaging problem
2. it comes from libplds4

**Comment by thgautier92** [comment] 2017-11-26 04:47
I confirm ! Installating nspr via brew is working and all CouchDb functions, including verification, views creation, and replications works. Thant you @TomArbuckle for your help.

**Comment by mirohs** [comment] 2017-11-27 11:09
I am using MacPorts, which has another installation directory for nspr: /opt/local/lib/nspr

To get CouchDB to work I manually copied the library files to: /usr/local/Cellar/nspr/4.17/lib

This works, but the approach is less than perfect. :-)

**Comment by lyudmil** [comment] 2017-11-28 11:34
@thgautier92, why has this issue been closed? Wouldn't people installing the CouchDB app for macOS still have problems if they just download it from the site? Has the app been patched, or are users expected to install nspr to have CouchDB work?

**Comment by martinleopold** [comment] 2017-11-28 14:34
@lyudmil: Exactly. The packaging issue still persists. Manually installing a dependency is a temporary workaround at best. I think the issue should be reopened, no?

**Comment by daveismith** [comment] 2017-11-28 21:52
I'm still getting this issue using just the downloaded couchdb app

**Comment by snollygolly** [comment] 2017-11-28 23:31
The fix to install packages is great, but this issue surely shouldn't be closed.  CouchDB doesn't work right out of the box without it, that can't be by design.

**Comment by koleto** [comment] 2017-12-10 11:55
It still doesn't work! Please reopen this issue!

**Comment by silverbackvasco** [comment] 2017-12-11 20:04
Could it be added to the documentation?

**Comment by martinleopold** [comment] 2017-12-17 14:05
There is an open issue adressing this problem here: https://github.com/apache/couchdb/issues/1004

**Comment by bedney** [comment] 2017-12-18 19:33
Just got bit by this today (again...) on High Sierra.

I'm using the double-clickable Mac installer and especially for the user base that uses this, there is certainly an expectation that CouchDB is just going to work "out of the box".

@janl - is there a complexity here that is preventing this from being fixed? I'm willing to help test a fix for this. Please let me know if I can help! Thanks!

**Comment by koleto** [comment] 2017-12-18 21:14
Actually there is no working package on macOS Sierra anymore for both CouchDB 1.x and CouchDB 2.x ...

**Comment by cuddle-sujeet** [comment] 2017-12-21 07:13
facing exactly the same issue with CouchDB 2.1.1. I can't create a new view.
[info] 2017-12-21T07:00:42.159819Z couchdb@localhost <0.218.0> -------- couch_proc_manager <0.27465.2> died normal

**Comment by ThibaultJanBeyer** [comment] 2017-12-24 16:17
This should be added to the documentation

**Comment by wohali** [comment] 2018-01-16 19:38
Reopening issue because this is a packaging problem.

**Workaround**: brew install nspr

**Comment by janl** [comment] 2018-01-18 07:39
Thank you for your patience everybody. Could you all please give this a spin. And make sure to `brew uninstall nspr` (or `brew unlink nspr`) first:

http://jan.prima.de/u/Apache-CouchDB-2.1.1.zip

**Comment by janl** [comment] 2018-01-18 08:22
New binary: http://jan.prima.de/u/Apache-CouchDB-2.1.1-fix2.zip

**Comment by lornajane** [comment] 2018-01-22 09:08
This package fixes the problem for me.  With `nspr` uninstalled, the build from the main website doesn't verify and can't create views.  This build can do both of those and seems to be working well.  Thanks!

**Comment by alleycat58uk** [comment] 2018-01-25 18:48
Works for me too.  Thanks

**Comment by bedney** [comment] 2018-01-25 19:44
LGTM Jans :+1: - thanks!

**Comment by janl** [comment] 2018-01-29 11:06
Thanks all for testing, deployed here: https://github.com/apache/couchdb-www/commit/c7fc8fc9863b387f4ea7aa8cf63ab2737cfef392

**Closed by janl** 2018-01-29 11:06 UTC
Labels: macos, packaging
