### ISSUE TITLE
js <= 1.8.5 conflicts with couch-js-1:1.8.5-21.el6.x86_64

### ISSUE THREAD

**Issue by malexdev** [apache/couchdb#2059] opened 2019-06-20 22:09 UTC
## Description

I am trying to install CouchDB via yarn on CentOS 6, following the steps outlined here: https://docs.couchdb.org/en/stable/install/unix.html#enabling-the-apache-couchdb-package-repository

When I do so, I receive the error: `js <= 1.8.5 conflicts with couch-js-1:1.8.5-21.el6.x86_64`.

I do not have the `js` package installed:

* `yum remove js*` returns `Package(s) js* available, but not installed. No Packages marked for removal`.
* `yum list installed js*` returns `Error: No matching Packages to list`.
* `rpm -q js` returns `package js is not installed`
* `rpm -q --whatprovides js` returns `no package provides js`

I disabled `bintray-apache-couchdb-rpm.repo` and ran `yum remove js`, same result.
I thought to try installing `js` to see if there was some odd situation causing it, but it turns out `js` is provided by the `bintray-apache-couchdb-rpm.repo` and isn't on my system or repolist at all.

So finally, I am forced to conclude that there is something in the repo causing this conflict.
Any guidance would be appreciated.

## Steps to Reproduce

1. `yum install couchdb`
2. Observe issue.

## Expected Behaviour

* CouchDB to install.

## Your Environment

* CouchDB Version used: None, yet.
* Browser name and version: None, yet.
* Operating System and version: CentOS release 6.1 (Final)

## Additional context

None, so far.

**Comment by touy** [comment] 2019-09-10 15:02
I have the same issue on my Centos 6.10 , 
Loaded plugins: fastestmirror
1:couch-js-1.8.5-21.el6.x86_64 has installed conflicts js <= ('0', '1.8.5', None): 1:couch-js-1.8.5-21.el6.x86_64
1:couch-js-devel-1.8.5-21.el6.x86_64 has installed conflicts js-devel <= ('0', '1.8.5', None): 1:couch-js-devel-1.8.5-21.el6.x86_64
Error: check all

**Comment by wohali** [comment] 2019-09-15 07:53
Hi there,

I don't doubt that you're having this problem, but I cannot reproduce this here.

I have tried:
* Inside a CentOS 6.10 VM, installed from the latest ISO itself
* Inside `docker run centos:6`.

Can you please try following these instructions:

http://docs.couchdb.org/en/latest/install/unix.html

which are slightly different than the old instructions? Thanks.

**Comment by demenyjo** [comment] 2019-10-03 15:00
I have returned to this issue, taking over for malexdev on the exact same server. While I do not know what all steps he took, I was able to get couchdb installed after performing a `yum update`.

**Comment by wohali** [comment] 2019-10-03 16:10
Great, thanks for the info. Closing this out.

**Closed by wohali** 2019-10-03 16:10 UTC
Labels: question
