### ISSUE TITLE
CI appears broken on `main`

### ISSUE THREAD

**Issue by bessbd** [apache/couchdb#3394] opened 2021-03-02 15:39 UTC
All commits merged to `main` are failing since Feb 26.
They fail with
```
21:05:37  ==> erlfdb (compile)
21:05:38  Compiling c_src/atoms.c
21:05:38  Compiling c_src/main.c
21:05:38  In file included from c_src/main.c:18:
21:05:38  c_src/fdb.h:17:10: fatal error: 'foundationdb/fdb_c.h' file not found
```
which is weird, because https://github.com/apache/couchdb-ci/blob/main/bin/apt-dependencies.sh#L190 installs FoundationDB just like https://github.com/apache/couchdb-config/blob/main/.travis.yml .
(And branch / PR CI looks fine)

**Comment by bessbd** [comment] 2021-03-02 15:40
I'd be happy to open a PR for this if someone helps me figure out why it's broken.

**Comment by wohali** [comment] 2021-03-02 19:24
@bessbd I'll have a look at this later today and we can talk through together what's up.

If you try to follow the steps in https://github.com/apache/couchdb/blob/main/build-aux/Jenkinsfile.full (this is run after any merge to `main`) by hand, using the Docker images, can you reproduce it?

It may be as simple as re-building the Docker containers and re-pushing them. This is not currently done automatically.

**Comment by wohali** [comment] 2021-03-02 23:01
This isn't something that can be fixed with a checkin. The **macOS** machine is failing to build: https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/49/pipeline

@janl We need your help to fix this.

We also have FreeBSD machines that are presently offline. There was a stoarge failure AND backup failure (due to bugs in both ZFS and Ceph!) and the machines need to be rebuilt. This is presently masked by the macOS failures. I will rebuild them this evening,

FYI, PRs only build on 3x Debian x86 instances, which is why they pass. Those images have fdb in them, as you pointed out.

**Comment by wohali** [comment] 2021-03-03 00:24
I've gotten the ARM node back online. I've relaunched the couchdb-arm-1 node on AWS. For posterity here is the configuration:

![Snap 2021-03-02, 18_25_03](https://user-images.githubusercontent.com/112292/109728724-c707aa80-7b84-11eb-9c54-a9174cd2f0f6.png)

While @davisp 's ansible setup could be used to manage this host as well, I did it by hand for expedience.

I ssh'ed into the machine and ran this to get prereqs installed, to create the Jenkins user, and to install the [ASF Infra pubkey](https://raw.githubusercontent.com/apache/infrastructure-p6/production/modules/nightlies/files/jenkins.pub):

```bash
sudo apt update
sudo apt upgrade -y
sudo apt install -y openjdk-11-jre
sudo groupadd -g 910 jenkins
sudo useradd -u 910 -g 910 -m jenkins
sudo mkdir /home/jenkins/.ssh
echo "<PUBKEY FROM PRIVATE REPO>" | sudo tee /home/jenkins/.ssh/authorized_keys >/dev/null
sudo chown -R jenkins:jenkins /home/jenkins/.ssh
sudo chmod -R og-rwx /home/jenkins/.ssh
```

then, for Docker from https://docs.docker.com/engine/install/debian/:

```bash
sudo apt install -y apt-transport-https ca-certificates curl gnupg
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io
# check functionality
sudo docker run hello-world
```

I then went to [Jenkins](https://ci-couchdb.apache.org/computer/couchdb-arm-1/configure) and updated the IP address to the new elastic IP address from AWS, and updated the hostkey with the contents of the node's `/etc/ssh/ssh_host_ecdsa_key.pub` . I pressed the Save button, then the Launch Agent button. The log showed it connected, downloaded, and ran the Jenkins agent.

The node then needed the nightly cronjobs [from here](https://github.com/apache/infrastructure-p6/blob/production/modules/build_nodes/manifests/jenkins.pp#L520-L551), which I added by hand. The `kill-old-docker.sh` script is in the same repo.

-----

Still TODO: the FreeBSD nodes, and when Jan can get to it, the Mac node.

**Comment by wohali** [comment] 2021-03-03 08:23
The FreeBSD nodes are now back online. As far as I can tell, `main` has never successfully built on these nodes, so there is still work to be done.

See https://github.com/apache/couchdb-erlfdb/pull/15 if you'd like to help.

**Comment by janl** [comment] 2021-03-05 09:58
the arm build seem to be failing again with the OP error message, so Jenkins doesn’t go all the way to the Mac build.

The fix in couchdb-erlfdb fix https://github.com/apache/couchdb-erlfdb/commit/c25d52470576fb210d5e3acc98e2cd0da33a397c#diff-427d8ddce21ccc4fae24fb547c7a82c2a793ed57208d8343e519e0aec8119ff7 should also have fixed things on Mac.

**Comment by wohali** [comment] 2021-03-05 17:50
Thanks @janl !

Looks like a minor naming mistake in `couchdb-ci/build.sh` prevented the arm and ppc images from getting pushed to docker hub correctly. I'm rebuilding the containers now, just to freshen them, pushing, and that should get us back in business.

**Comment by wohali** [comment] 2021-03-05 19:36
OK, as it turns out, Apple don't provide packages for fdb on anything but x86_64 for Linux, so I had to add support for building that from scratch. That's building now (it's sloooowwwww). Once it's done I'll push a new arm64v8 container and the jobs should start passing. Note that as we don't have any ppc64le workers, I didn't bother rebuilding that image.

For those interested in how all this gubbins works, there is a job in Jenkins called "Update Docker Containers" that runs on all of the nodes and pulls the latest docker container every 24h. I've just updated it to also pull all the containers on arm and ppc (if workers ever come back.)  If you have to push a new container and want it working _now_, just run the job by hand.

**Comment by wohali** [comment] 2021-03-07 06:01
Update: fdbserver/fdbcli won't run inside of a cross-arch docker container, with the same error as https://forums.foundationdb.org/t/foundationdb-does-not-run-on-windows-subsystem-for-linux-wsl/809/10 . This causes a problem on install of the program, which I'm doing after building its package. It tries to run `fdbcli` and fails.

I've worked around this with a `|| true` in the build script.

I tested the docker container on our `arm64v8` worker, and it works, so I'm completing the automated build overnight and will push the image in the morning. At that point, we should be building `main` on all available secondary platforms again - Linux arm64v8, macOS, FreeBSD.

**Comment by BillStephenson** [comment] 2021-03-07 06:06
Does this mean it could run on a Raspberry Pi 4?

Cuz that would be really cool :D

—

Bill Stephenson

**Comment by wohali** [comment] 2021-03-07 06:19
CouchDB 3.x already does, and packages (that run under Raspbian) have been available for at least a year now.

This is specifically talking about `main`, aka future CouchDB 4.0, which is not yet released.

**Comment by BillStephenson** [comment] 2021-03-07 06:26
I was under the impression that CouchDB wouldn’t run on the new “Pi 4 8GB” because it uses an ARM chip (or something like that). 

It still runs on a P3 though and they’re still selling them so that’s good.

— 

Bill

**Comment by wohali** [comment] 2021-03-07 06:50
This isn't the ticket for this, but the new Raspberry Pis are `arm64v8` which is directly supported by our binary packages.

Raspberry Pi 1 and 2 are 32-bit `armhf`, and will run CouchDB, but not from our prebuilt packages.

Raspberry Pi 3 ships as `armhf` but can be set up to run as `arm64v8,` but is unsupported. I believe our packages will run in these reconfigured machines, but it is untested.

**Comment by BillStephenson** [comment] 2021-03-07 06:54
Wow… that is awesome. I’ve obviously not kept up

Thank You!

**Comment by bessbd** [comment] 2021-03-07 21:31
> I'm completing the automated build overnight and will push the image in the morning. At that point, we should be building `main` on all available secondary platforms again - Linux arm64v8, macOS, FreeBSD.

Thank you, @wohali !

**Comment by wohali** [comment] 2021-03-08 19:29
@bessbd OK, so all of the _technical_ limitations to CI on `main` have been lifted. Now, we need some code fixes.

Would you be willing to start here?

```
https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/70/pipeline/252#step-253-log-186
```

I imagine there will be more. If you'd like to dig thru them yourself, I recommend following along in `Jenkinsfile.full`, pulling down each Docker container, and going through the build process, including the packaging steps. Obviously the packages are going to need updating for 4.x, but it can't hurt to get started on them now. And I sure would appreciate the help!

**Comment by bessbd** [comment] 2021-03-09 17:49
> @bessbd OK, so all of the _technical_ limitations to CI on `main` have been lifted. Now, we need some code fixes.
> 
> Would you be willing to start here?
> 
> ```
> https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/70/pipeline/252#step-253-log-186
> ```
> 
> I imagine there will be more. If you'd like to dig thru them yourself, I recommend following along in `Jenkinsfile.full`, pulling down each Docker container, and going through the build process, including the packaging steps. Obviously the packages are going to need updating for 4.x, but it can't hurt to get started on them now. And I sure would appreciate the help!

On it! So far I haven't been able to reproduce the issue you've mentioned. (But I was trying it native. I'll try with docker next.)

**Comment by bessbd** [comment] 2021-03-09 19:20
I was doing a `docker run -u root -it  couchdbdev/ubuntu-bionic-erlang-20.3.8.25-1:latest  bash -c "git clone https://github.com/apache/couchdb.git && cd couchdb && ./configure --spidermonkey-version 1.8.5 && make"`.
I assumed it's the same contents that is `make`d for packaging and for the "regular build/test".  And I assumed that it's the same options for `CC`. (And certainly not stricter for packaging than for regular build.)

I guess I'll have to try and go further and execute the packaging things too.

**Comment by bessbd** [comment] 2021-03-11 22:57
Update: I think the issue linked above (`uninitialized`) has been fixed by  https://github.com/apache/couchdb-erlfdb/releases/tag/v1.2.9 and https://github.com/apache/couchdb/commit/c00bdd7ba93e7cdfcf8faebc9d9306931d5ffa0b . 
Also, the current issues will probably be resolved by https://github.com/apache/couchdb/pull/3414 .

**Comment by bessbd** [comment] 2021-03-16 13:39
Also related: https://github.com/apache/couchdb/pull/3429

**Comment by bessbd** [comment] 2021-03-17 12:32
Right now I'm working on the `17-multi-type-value-test.py` failures. They seem consistent on centos 6. I have an idea, I'll post here later.

**Comment by bessbd** [comment] 2021-03-18 18:32
Related PR: https://github.com/apache/couchdb/pull/3439

**Comment by afsanjar** [comment] 2021-03-23 21:29
> Thanks @janl !
> 
> Looks like a minor naming mistake in `couchdb-ci/build.sh` prevented the arm and ppc images from getting pushed to docker hub correctly. I'm rebuilding the containers now, just to freshen them, pushing, and that should get us back in business.

Hi, my name Amir Sanjar leading the IBM power-enabled team. I apologize for losing access to your ppc64le worker, let me help you here. What is your HW requirement (i.e. cores, storage, public net access, Linux distro..)

**Comment by bessbd** [comment] 2021-03-25 12:20
There are many docker pull rate limit issues. I'll put this on hold until we get to have the images in a place where rate limits don't affect us.

**Comment by wohali** [comment] 2021-03-25 16:33
@bessbd While we wait for ASF, those should only be happening around midnight, North America time. They'll be colliding with the job that keeps our Docker images fresh on each machine - so that we don't have to `docker pull` for every job we run. I can try reducing the frequency to every few days if you would like to try that.

Are you seeing them during the US business hours?

**Comment by bessbd** [comment] 2021-03-25 17:18
https://ci-couchdb.apache.org/job/jenkins-cm1/job/FullPlatformMatrix/job/main/110/ says 10am UTC-ish. Depending on the coast, it could be close to midnight somewhere in the US.

**Comment by wohali** [comment] 2021-03-25 17:29
OK, I've reduced the frequency of the mass downloader script to once a week, on Sunday mornings. Let's see if that helps.

If we push any new Docker images (and Infra doesn't come through with the new namespace for us) we'll have to manually trigger that job, which may temporarily put us over the rate limit.

Can you pick this ticket back up now?

**Comment by wohali** [comment] 2021-03-25 17:53
For reference, the FreeBSD box is:

```
CPU: Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz (3300.00-MHz K8-class CPU)
real memory  = 8589934592 (8192 MB)
avail memory = 8271409152 (7888 MB)
```

shared across 2 Jenkins workers, each in their own jail.

**Comment by bessbd** [comment] 2021-03-26 10:59
> OK, I've reduced the frequency of the mass downloader script to once a week, on Sunday mornings. Let's see if that helps.
> 
> If we push any new Docker images (and Infra doesn't come through with the new namespace for us) we'll have to manually trigger that job, which may temporarily put us over the rate limit.
> 
> Can you pick this ticket back up now?

I've re-assigned myself. Let's see how it goes.

**Comment by nickva** [comment] 2021-04-02 21:06
It was interesting that we didn't hit this issue on CentOS 7 on 3.x so I was curious and traced the `less` call when running that mango test:

```
10:9:04.429561 <0.11140.1> couch_ejson_compare:less_nif([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.429783 <0.11140.1> couch_ejson_compare:less_nif/2 error badarg

10:9:04.429984 <0.11140.1> couch_ejson_compare:less_erl([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.430254 <0.11140.1> couch_ejson_compare:less_list([{<<"ÿÿÿÿ">>}], [{[{<<"forename">>,<<"Eddie">>}]}])

10:9:04.430506 <0.11140.1> couch_ejson_compare:less_erl({<<"ÿÿÿÿ">>}, {[{<<"forename">>,<<"Eddie">>}]})

10:9:04.430745 <0.11140.1> couch_ejson_compare:less_erl/2 --> 1

10:9:04.430903 <0.11140.1> couch_ejson_compare:less_list/2 --> 1

10:9:04.431088 <0.11140.1> couch_ejson_compare:less_erl/2 --> 1
```

Apparently in `3.x` we compare an object `{[{<<"forename">>,<<"Eddie">>}]}` against a (highest?) marker, but that marker is not an object but a tuple with one element `{<<"ÿÿÿÿ">>}`. `less_nif/2` then notices the object is not valid ejson and throws a `badarg` error.  The the code then falls back to Erlang using `less_erl/2` and at least in this case return the correct result (highest marker is greater than (`1`) than the object).

In `main` we compare against an actual object `{[{<<"ÿÿÿÿ">>, <<>>}]}` so everything gets unpacked nicely then the old unicode library at least older than 59 (and possible 53) didn't error out, but also didn't sort the `<<255,255,255,255>>` as the highest element as intended. Here is centos 7 with libicu-50.2-4.el7_7.x86_64, for example
```
couch_ejson_compare:less(<<"forename">>, <<255,255,255,255>>).
1
> couch_ejson_compare:less(<<"/">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"0">>, <<255,255,255,255>>).
1
```

and on mac os with icu4c 59:
```
> couch_ejson_compare:less(<<"forename">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"/">>, <<255,255,255,255>>).
-1
> couch_ejson_compare:less(<<"0">>, <<255,255,255,255>>).
-1
```

**Comment by nickva** [comment] 2021-04-02 21:08
I have an alternative fix that should be a bit more general https://github.com/apache/couchdb/pull/3490 to the above issue

**Comment by bessbd** [comment] 2021-04-02 21:16
Thank you for taking the time and doing the investigation, @nickva !

**Closed** 2021-04-08 17:21 UTC
