### ISSUE TITLE
Windows installer fails with "CouchDB Setup Wizard ended prematurely"

### ISSUE THREAD

**Issue by ahaus** [apache/couchdb#2554] opened 2020-02-15 17:38 UTC
## Description
I tried to install the new CouchDB 3.0.0-RC1 using the installer for Windows.

I went through the setup process using the default values.
The installation process shows some progress with copying files however it rolls back at the end
and shows the dialog with the message "Apache CouchDB setup Wizard ended prematurely".

I am logged in with Administrator privileges.

## Steps to Reproduce

Just run the installer on Windows 10 Pro with default values.

## Expected Behaviour

CouchDB is installed correctly and registered as a service.

## Your Environment
* CouchDB version used: 3.0.0-RC.1 (apache-couchdb-3.0.0.1.msi) 
* Browser name and version:
* Operating system and version: Windows 10 Pro 64-bit (German), Version 19.03 Build: 18362.657

**Comment by ahaus** [comment] 2020-02-15 17:41
![couchdb-failed-install](https://user-images.githubusercontent.com/1169145/74592547-b68c9c80-5022-11ea-872c-635ade5760cc.png)
Added Screenshot for failed installation.

**Comment by ahaus** [comment] 2020-02-15 17:44
Windows Event Logs shows:
Product: Apache CouchDB -- Installation failed.

Windows Event message:
`Protokollname: Application
Quelle:        MsiInstaller
Datum:         15.02.2020 18:32:57
Ereignis-ID:   11708
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      MODOCU-007\andreas
Computer:      MODOCU-007
Beschreibung:
Product: Apache CouchDB -- Installation failed.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">11708</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-02-15T17:32:57.021024000Z" />
    <EventRecordID>5057</EventRecordID>
    <Channel>Application</Channel>
    <Computer>XXXXXX</Computer>
    <Security UserID="S-1-5-21-143990235-1749869768-1250630748-1001" />
  </System>
  <EventData>
    <Data>Product: Apache CouchDB -- Installation failed.</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B34434437373645302D464144462D343833312D414635362D4538304533394633344346437D</Binary>
  </EventData>
</Event>`

**Comment by ahaus** [comment] 2020-02-15 17:49
Windows Event Logs shows another message with error code: 1603

> Das Produkt wurde durch Windows Installer installiert. Produktname: Apache CouchDB. Produktversion: 3.0.0. Produktsprache: 1033. Hersteller: The Apache Software Foundation. Erfolg- bzw. Fehlerstatus der Installation: 1603.

Event Message (XML):
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">1033</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-02-15T17:32:57.021024000Z" />
    <EventRecordID>5058</EventRecordID>
    <Channel>Application</Channel>
    <Computer>XXXXXX</Computer>
    <Security UserID="S-1-5-21-143990235-1749869768-1250630748-1001" />
  </System>
  <EventData>
    <Data>Apache CouchDB</Data>
    <Data>3.0.0</Data>
    <Data>1033</Data>
    <Data>1603</Data>
    <Data>The Apache Software Foundation</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B34434437373645302D464144462D343833312D414635362D4538304533394633344346437D3030303032303962336337333131663365656538666466303436376138663764366263363030303030393034</Binary>
  </EventData>
</Event>`

**Comment by wohali** [comment] 2020-02-15 18:37
@ahaus Thanks for this report. I've tested on Win10 Pro (English) locally and can't reproduce.

Can you please do the following. From an administrative command prompt, change to the directory in which the `.msi` is stored, then run:

```
msiexec /l* log.txt /i apache-couchdb-3.0.0.msi
```

do the exact same thing you did to cause the failure above, and attach the `log.txt` file to this bug? Thanks.

**Comment by ahaus** [comment] 2020-02-16 19:30
[log.txt](https://github.com/apache/couchdb/files/4210718/log.txt)
Attached log.txt

**Comment by wohali** [comment] 2020-02-17 01:12
I won't be able to look at this until Tuesday earliest. Here's the problem:

```
Action 20:19:57: WriteAdminIniFile. 
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSI14D0.tmp-\
SFXCA: Failed to get requested CLR info. Error code 0x80131700
SFXCA: Ensure that the proper version of the .NET Framework is installed, or that there is a matching supportedRuntime element in CustomAction.config. If you are binding to .NET 4 or greater add useLegacyV2RuntimeActivationPolicy=true to the <startup> element.
CustomAction WriteAdminIniFile returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 20:19:58: InstallFinalize. Return value 3.
```

What happens if you install the .NET Framework 3.5 SP1 offline installer first?

https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10  Use the Control Panel way to install this.

**Comment by jiangphcn** [comment] 2020-02-17 10:18
I can run `CouchDB 3.0.0-RC1 installer` on one of Windows 10 box, and it is working. 

From Windows registry, `.Net Framework 3.5.30729.4926` was installed on this box.

**Comment by ahaus** [comment] 2020-02-17 10:22
@jiangphcn Thanks for the hint. Installing the .NET Framework 3.5 SP1 resolved the issue.

**Comment by jiangphcn** [comment] 2020-02-17 12:29
Great and closing

**Closed by jiangphcn** 2020-02-17 12:29 UTC
Labels: bug, needs-triage

**Comment by oldrich-svec** [comment] 2020-02-28 06:40
I also ended in the same trap on Windows Server 2019 + CouchDB 3.0.0. Maybe you could mention it in the upgrade guide?:

https://docs.couchdb.org/en/stable/install/upgrading.html

**Comment by wohali** [comment] 2020-02-28 16:03
@oldrich-svec It's on the download page:

https://neighbourhood.ie/download-apache-couchdb-win/

And it's on the "Installation on Windows page":

https://docs.couchdb.org/en/stable/install/windows.html

Do you think we need it on the upgrading page, too?

**Comment by wohali** [comment] 2020-02-28 16:48
I've added a notice to the Release Notes page in https://github.com/apache/couchdb-documentation/pull/500

That will shortly show up on docs.couchdb.org (the RTD queue is busy).

**Comment by Sid-Turner-Ellis** [comment] 2020-12-24 21:03
I am also getting this error, It will not allow me to install and tells me the setup wizard ended prematurely. Was there any solution to this?

**Comment by wohali** [comment] 2020-12-25 03:01
@Sid-Turner-Ellis Install the .NET Framework 3.5 first. Does that work?

**Comment by Sid-Turner-Ellis** [comment] 2020-12-25 12:15
@wohali Which should i download? There is 3.1 and 5.0 and then run times vs the sdk

**Comment by Sid-Turner-Ellis** [comment] 2020-12-25 12:40
@wohali That worked a treat. Thanks a lot
