### ISSUE TITLE
Mango queries with `conflicts: true` return documents that do not have conflicts

### ISSUE THREAD

**Issue by garbados** [apache/couchdb#1101] opened 2018-01-10 20:35 UTC
Queries to the `/{db}/_find` endpoint that set `conflicts: true` return documents that do not include conflicts. I have documented a test case [here](https://gist.github.com/garbados/335bc7c1836cbf726a6b511d6c0fa418) that reproduces the issue.

The documentation in [cloudant/mango]() indicates that this is expected behavior:

> conflicts (optional) (default: false) - boolean, whether or not to include information about any existing conflicts for the document.

However, it sure would be nice to issue queries that return *only* conflicted documents that match the given selector.

## Expected Behavior

A query setting should exist to filter query results to only those that have conflicted and match the given selector.

## Current Behavior

Setting `conflicts: true` returns documents with and without conflicts, such that the user must perform a second query to `/_all_docs` to determine which documents actually have conflicts.

## Possible Solution

Setting `onlyConflicts` or otherwise-named query value should cause CouchDB to filter results of a query to only those documents that match a given selector *and* which have conflicts.

## Steps to Reproduce (for bugs)

I've developed a test case [here](https://gist.github.com/garbados/335bc7c1836cbf726a6b511d6c0fa418) using node.js.

## Context

Detecting conflicts requires finding them first. In large databases, performing one query to find documents that may have conflicts and then another to determine which of them actually do creates considerable request overhead for applications attempting to detect or resolve conflicts proactively.

## Your Environment

* Version used: 2.1.1-180a155
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Ubuntu 16.04.3 LTS
* Link to your project: [gist](https://gist.github.com/garbados/335bc7c1836cbf726a6b511d6c0fa418)

**Comment by davisp** [comment] 2018-01-19 21:23
Going over this on IRC I'm pretty sure the root cause of this bug is here:

https://github.com/apache/couchdb/blob/master/src/mango/src/mango_cursor_view.erl#L285-L287

Using a partial filter index and removing the _conflicts check results in the correct results. Theoretically specifying r=2 in the options would also fix it but Fauxton apparently has issues encoding that and is passing [50] (i.e., ASCII "2") which is then ignored by Mango.

**Comment by wohali** [comment] 2018-03-27 01:21
@garbados can you see if specifying `r=2` in the options works with this, when NOT using Fauxton, as @davisp suggests above?

**Comment by garbados** [comment] 2018-03-27 16:04
Given a database with conflicts, here are the index and selector I am using:

```
```
const SELECTOR = {
  selector: { _conflicts: { $exists: true } },
  use_index: 'conflicts'
}

**Comment by garbados** [comment] 2018-03-27 16:09
Here are the index and selector I am using to detect conflicts:

```
// INDEX
{
  "index": {
    "fields": [
      "_conflicts"
    ],
    "partial_filter_selector": {
      "_conflicts": {
        "$exists": true
      }
    }
  },
  "ddoc": "conflicts",
  "type": "json"
}

// SELECTOR
{
  "selector": {
    "_conflicts": {
      "$exists": true
    }
  },
  "use_index": "conflicts"
}
```

Given a database with conflicted documents, using this selector with this index returns this result:

```
{
  "docs":[],
  "bookmark": "nil"
}

```

I'm not sure what I'm doing wrong relative to the prescribed method.

**Comment by LyteFM** [comment] 2018-04-06 13:24
I was tired of adding and deleting DDocs when searching for conflicts in a DB so I've tried this simple Mango-query in Fauxton:
```
{
   "selector": {
      "_conflicts": {
         "$exists": true
      }
   }
}
```
But no documents were returned even though conflicts existed. Might be because the "_conflicts" - key is not visible by default. It would help a lot if this was possible via Fauxton.

**Comment by janl** [comment] 2018-07-08 13:51
Closing in favour of https://github.com/apache/couchdb/pull/1425

**Closed by janl** 2018-07-08 13:51 UTC
Labels: mango
