### ISSUE TITLE
req_err(50502807) unknown_error : normal

### ISSUE THREAD

**Issue by Kaspanoombro** [apache/couchdb#2877] opened 2020-05-08 08:23 UTC
This random error appears in the log. I activated the debug mode to get more details but i am unable to decifer what error is and where is and why it happens

## Description
Partial copy of the log:
[debug] 2020-05-08T07:54:05.818181Z couchdb@127.0.0.1 <0.6787.57> f9f1470373 Successful cookie auth as: "user"
[notice] 2020-05-08T07:54:06.766886Z couchdb@127.0.0.1 <0.7607.100> e675d3f805 127.0.0.1:5984 127.0.0.1 user GET /mydb/_changes?feed=continuous&style=all_docs&since=%22396-g1AAAACbeJzLYWBgYMpg$
[debug] 2020-05-08T07:54:06.768871Z couchdb@127.0.0.1 <0.7607.100> 5b2dc2420e no record of user user
[debug] 2020-05-08T07:54:06.768928Z couchdb@127.0.0.1 <0.7607.100> 5b2dc2420e timeout 600
[debug] 2020-05-08T07:54:06.768963Z couchdb@127.0.0.1 <0.7607.100> 5b2dc2420e Successful cookie auth as: "user"
[error] 2020-05-08T07:54:07.542928Z couchdb@127.0.0.1 <0.11674.83> 348003536f req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-05-08T07:54:07.558846Z couchdb@127.0.0.1 <0.11964.83> 4fba79e468 req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-05-08T07:54:07.559091Z couchdb@127.0.0.1 <0.10992.83> ab561f7912 req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-05-08T07:54:07.689964Z couchdb@127.0.0.1 <0.11602.83> f6499308fb req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-05-08T07:54:07.701773Z couchdb@127.0.0.1 <0.12166.83> 67908d1095 req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
## Steps to Reproduce

I have no ideia

## Expected Behaviour
No errors

## Your Environment
Ubuntu 16.04.6 LTS
64 bits

local.d/10-replicator.ini 
[replicator]
worker_processes = 2
worker_batch_size = 200
http_connections = 10

{"couchdb":"Welcome","version":"3.1.0","git_sha":"ff0feea20","uuid":"ccee068ee136a08b5f57ec565fa89fdd","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

1 singles couchdb install that replicates to a single remote instance over the internet.

* CouchDB version used: 3.1.0
* Browser name and version: (client computer) Versão 81.0.4044.122 (Versão oficial) Built on Ubuntu  
* Operating system and version: (client computer) running on Ubuntu 19.10 64 bits

**Comment by ChetanGoti** [comment] 2020-06-26 04:37
If I'm able to recall this correctly, this happens when you start a changes feed and stop it.

**Comment by nickva** [comment] 2021-12-10 19:33
Thanks for reaching out, @ChetanGoti and @Kaspanoombro.

This issue looks like a duplicate of https://github.com/apache/couchdb/issues/1600 and should be fixed in the latest 3.x release

**Closed by nickva** 2021-12-10 19:33 UTC
Labels: bug, needs-triage
