### ISSUE TITLE
Sporadic 500 on writing attachment

### ISSUE THREAD

**Issue by jvegaseg** [apache/couchdb#1096] opened 2018-01-07 20:49 UTC
We have a 6-node cluster configured with q=16. We are migrating attachments from our old storage system to CouchDB. We first create the document in CouchDB database and immediately we issue a request in order to add the attachment associated to the document previously created.

Everything work well but sometimes we receive a 500 Internal Server Error when trying to add an attachment. After the error, we wait 10 seconds and retry the same request and it works without problems.

We would like to know the cause of these sporadic errors. 

Servers are very idle (CPU and disk activity).

## Expected Behavior

It should add the attachment to the document without errors.

## Current Behavior

Sporadically, it gets an 500 error due to a "mfa: fabric_rpc:update_docs/3 exit:timeout". 

## CouchDB logs

In server who answer the request:

> [error] 2018-01-07T19:12:15.517475Z couchdb@X.X.X.122 <0.14999.1143> f0ef070d10 fabric_worker_timeout update_docs,'couchdb@X.X.X.124',<<"shards/10000000-1fffffff/ficheros.1514665102">>

In other server for same request:

> [error] 2018-01-07T19:21:15.517744Z couchdb@X.X.X.123 <0.25589.1086> f0ef070d10 rexi_server: from: couchdb@X.X.X.122(<13938.14999.1143>) mfa: fabric_rpc:update_docs/3 exit:timeout [{fabric_doc_attachments,'-receiver/2-fun-3-',1,[{file,"src/fabric_doc_attachments.erl"},{line,43}]},{couch_att,write_streamed_attachment,3,[{file,"src/couch_att.erl"},{line,577}]},{couch_db,with_stream,3,[{file,"src/couch_db.erl"},{line,1335}]},{couch_db,'-doc_flush_atts/2-lc$^0/1-0-',2,[{file,"src/couch_db.erl"},{line,1286}]},{couch_db,doc_flush_atts,2,[{file,"src/couch_db.erl"},{line,1286}]},{couch_db,'-update_docs/4-lc$^8/1-8-',2,[{file,"src/couch_db.erl"},{line,1141}]},{couch_db,'-update_docs/4-lc$^7/1-7-',2,[{file,"src/couch_db.erl"},{line,1140}]},{couch_db,update_docs,4,[{file,"src/couch_db.erl"},{line,1140}]}]

In other server for same request:

> [error] 2018-01-07T19:21:15.518778Z couchdb@X.X.X.124 <0.17893.1127> f0ef070d10 rexi_server: from: couchdb@X.X.X.122(<13938.14999.1143>) mfa: fabric_rpc:update_docs/3 exit:timeout [{fabric_doc_attachments,'-receiver/2-fun-3-',1,[{file,"src/fabric_doc_attachments.erl"},{line,43}]},{couch_att,write_streamed_attachment,3,[{file,"src/couch_att.erl"},{line,577}]},{couch_db,with_stream,3,[{file,"src/couch_db.erl"},{line,1335}]},{couch_db,'-doc_flush_atts/2-lc$^0/1-0-',2,[{file,"src/couch_db.erl"},{line,1286}]},{couch_db,doc_flush_atts,2,[{file,"src/couch_db.erl"},{line,1286}]},{couch_db,'-update_docs/4-lc$^8/1-8-',2,[{file,"src/couch_db.erl"},{line,1141}]},{couch_db,'-update_docs/4-lc$^7/1-7-',2,[{file,"src/couch_db.erl"},{line,1140}]},{couch_db,update_docs,4,[{file,"src/couch_db.erl"},{line,1140}]}]

 

## Possible Solution

Retrying the request works well.

## Configuration
We use default settings except:

local.ini
```
[cluster]
q = 16

[log]
level = warning
```

vm.args
```
-name couchdb@X.X.X.120
-setcookie XXXXXXXXXXXXXX
-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9200

-kernel error_logger silent
-sasl sasl_error_logger false

+K true
+A 16
+Bd -noinput
```

sys.config

```
[
    {lager, [
        {error_logger_hwm, 1000},
        {error_logger_redirect, true},
        {handlers, [
            {lager_console_backend, [debug, {
                lager_default_formatter,
                [
                    date, " ", time,
                    " [", severity, "] ",
                    node, " ", pid, " ",
                    message,
                    "\n"
                ]
            }]}
        ]},
        {inet_dist_listen_min, 9100},
        {inet_dist_listen_max, 9200}
    ]}
].
```

## Environment
Software is running on virtualized Centos 7 using OpenVZ 7.
Each node has same configuration.
Each node has 16 cores.

Some command outputs.
**free -h**
```
              total        used        free      shared  buff/cache   available
Mem:            40G        319M         28K        1,3M         39G         36G
Swap:          100G        4,6M         99G
```

**top**
```
top - 22:02:37 up 9 days, 22:35,  1 user,  load average: 0,41, 0,25, 0,23
Tasks:  37 total,   1 running,  36 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,5 us,  0,1 sy,  0,0 ni, 99,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 41943040 total,    70868 free,   284816 used, 41587356 buff/cache
KiB Swap: 10485760+total, 10485286+free,     4740 used. 38381588 avail Mem  

```

**df -h**
```
S.ficheros        Tamaño Usados  Disp Uso% Montado en
/dev/ploop23569p1   9,9T    72G  9,4T   1% /
none                 31G      0   31G   0% /sys/fs/cgroup
none                 31G      0   31G   0% /dev
tmpfs                20G      0   20G   0% /dev/shm
tmpfs                20G   144K   20G   1% /run
tmpfs               4,0G      0  4,0G   0% /run/user/0
```

**Comment by jvegaseg** [comment] 2018-01-16 07:01
Anyone could help? There is a configuration option to increase that timeout?

**Comment by wohali** [comment] 2018-01-16 23:48
My guess is this is similar to what we're seeing in #796 .

We see this issue more frequently with people running in containers and virtualisation, especially Docker. /cc @kocolosk

**Comment by jvegaseg** [comment] 2018-01-17 21:45
I have just increased max open files from 1024 to 65535.
I will update the ticket is this solves the issue

**Comment by jvegaseg** [comment] 2018-01-18 06:20
Increasing max open files does not help. I have just changed max_dbs_open = 2500 in local.ini.
Waiting if that change helps.

**Comment by jvegaseg** [comment] 2018-01-18 06:29
Take in account that:

1.- Each virtual machine is the only machine running on each hardware node.
2.- Couchdb is the only service running in each machine

Regards

**Comment by wohali** [comment] 2018-01-18 17:28
Understood, this is similar to other issues that have recently been filed.

**Comment by davisp** [comment] 2018-01-19 18:58
You might try writing the doc creation with `?w=3` to see if that fixes things. I'd wager you're probably getting a race against the first write if you happen to snag a node that didn't get the write yet on the second request. If that seems to fix it we can take a look at attachment writing to see if we can make it robust if it tries to write to a node that would generate a conflict.

Oh, and alternatively a more straightforward test would be to create a doc, then write an attachment to it with an random revision. I'd think that might fail in roughly the same way.

**Comment by jvegaseg** [comment] 2018-01-20 07:35
It seems the problem is solved. Definitely increasing file descriptors has solved the problem (tonight there were no errors). 

First time I increased file descriptors I did it wrongly.

Thanks!!!

**Comment by jvegaseg** [comment] 2018-01-20 11:40
Sorry but errors appears again. 65000 file descriptors is enough of I have to increase it?

**Comment by wohali** [comment] 2018-01-20 20:58
It depends on the # of databases and # of shards you are creating (`q` value). This is increased by the number of design documents you have. As an example:

* 1 database
* q=16
* 10 different ddocs or Mango indexes

(1 + 10) * 16 = 176 file handles required to open this database and use those views.

Plus a couple more for things like couch logging and so on.

It is usually quite safe to set the limit of file descriptors quite high on modern servers.

**Comment by wohali** [comment] 2018-01-20 21:03
I'm closing this provisionally for now - looks like the problem is lack of file handles (for people who search through tickets in the future)

Please reopen if necessary.

**Comment by jvegaseg** [comment] 2018-01-20 21:32
Dear davisp , I have test with w=3 and everything works well. Take in account that we are experimenting this issue sporadically: 1 request for every 10.000, so it is very difficult to reproduce.
Every day we have 3 or 4 issues like this.

Also I have test with random revision and I get 409=Conflict response but in server is not generated any error or warning.

**Comment by jvegaseg** [comment] 2018-01-20 21:42
Dear wohali, we only have 3 database (with q=16) with no ddocs or Mango indexes. We use it by now for storing email attachments. 

(1 + 10) * 16 * 3 = 528

Max open files could reach until 65000.

**Comment by wohali** [comment] 2018-01-20 21:43
OK, reopening. @davisp Sounds like your race on attachment write is the issue.

**Comment by jvegaseg** [comment] 2018-01-28 16:04
Sometimes it returns 409-Conflict but waiting for a while and retrying it seams to work. DB is growing and these errors (500 and 409) appears more frequently.

**Comment by wohali** [comment] 2018-02-15 21:58
@jvegaseg can you confirm that the `?w=3` workaround provided by @davisp was insufficient to solve the problem?

**Comment by jvegaseg** [comment] 2018-03-17 23:02
@wohali I confirm you that the `?w=3` workaround does not solve the problem.

**Comment by jvegaseg** [comment] 2018-05-04 05:55
Any advance? Title should change from Sporadic to Frequent or Common (more than 50 daily)

**Comment by jvegaseg** [comment] 2018-05-15 10:38
Hello, it seams that increasing timeout in fabric solves the problem:

```
[fabric]
request_timeout = 300000
```

**Comment by wohali** [comment] 2018-05-15 16:37
This is a sign that your cluster is overloaded...but it is not a bug in CouchDB.

**Closed by wohali** 2018-05-15 16:37 UTC
Labels: bug, dbcore

**Comment by jvegaseg** [comment] 2018-05-20 17:12
Sorry but the problem arises again (also with request_timeout = 300000).
Machines are not overloaded (nor disk nor CPU). 
Uploading an attachment of very few kilobytes can not take 5 minutes in 3 nodes at same time (it reports the error on 3 nodes for same request).

Is there any limit about how many requests (for uploading attachments) can be handled?

As info, we have only 2 databases and both together has a size of 3 Terabytes.

**Comment by daweedm** [comment] 2020-10-20 10:43
I'm facing the same issue, @jvegaseg did you find a solution for this ?
