### ISSUE TITLE
ignored "-proto_dist inet6_tcp"

### ISSUE THREAD

**Issue by sergey-safarov** [apache/couchdb#2791] opened 2020-04-16 21:43 UTC
## Description

I cannot form cluster in ipv6 network

## Steps to Reproduce

1. add "-proto_dist inet6_tcp" into "/opt/couchdb/etc/vm.args"
2. open fauxton interface and add host using DNS name that resolved only AAAA record.

## Expected Behaviour

CouchDB try resolve AAAA record

## Your Environment

CouchDB resolve A record

* CouchDB version used: 2.3.1
* Browser name and version: Google Chrome
* Operating system and version: CentOS 8

## Additional Context

None

**Comment by wohali** [comment] 2020-04-17 20:12
@dch You did some work on IPv6 a while back, know anything about this?

**Comment by CanRau** [comment] 2022-05-30 16:34
Would also love to get CouchDB going using IPv6 to be able to deploy a cluster on [Fly.io](https://fly.io/)

**Comment by dch** [comment] 2022-05-30 20:20
works fine here on FreeBSD but that shouldn't matter. If you find a working config for fly, let us know.

for each node, just have couchdb@c01.fqdn ... couchdb@c02.fqdn etc for name field. the rest
of your ini & args files should be the same as usual.

# `vm.args` snippet

```
-name couchdb@c01.fqdn
-setcookie ...
-proto_dist inet6_tcp
-kernel inet_dist_listen_min 4370
-kernel inet_dist_listen_max 4400
...
```

# `local.ini` snippet

```
[chttpd]
port = 5984
bind_address = ::
...
```

consider changing the bind_address to something less open once you know what you're doing.

**Comment by CanRau** [comment] 2022-05-31 02:44
Trying that I get

```
{conn_failed,{error,nxdomain}}
```

when using `a899cafd-e205-f7b7-765a-00e271c28e17.vm.crcouchdb1.internal` as remote host, this is [fly's private networking](https://fly.io/docs/reference/private-networking/#fly-internal-addresses)
and `::` as bind address.

I'm also trying to debug with the Fly folks over at [community.fly.io](https://community.fly.io/t/cant-get-a-couchdb-cluster-working-connection-closed/5373/8), so far having issues querying the instances IPv6 to try that instead of the hostname as mentioned over there.

**Comment by big-r81** [comment] 2022-10-27 11:47
@CanRau Is this still an issue?

**Comment by CanRau** [comment] 2022-10-27 16:59
Sorry I don't know as I'm not working on this anymore, so at least for me it's not and could be closed.

**Comment by sergey-safarov** [comment] 2022-10-27 17:04
I can make a test.
Is required to make the test on the latest stable version?
Can I test using `apache/couchdb:latest` docker image?

**Comment by big-r81** [comment] 2022-10-27 17:35
Try it with the latest source from main or with 3.2.2. I can't say something to use inside docker, but you can test it...

**Comment by dch** [comment] 2022-10-30 20:23
This still works perfectly for me, since 2.3.x til 3.2.2 atm.

**Comment by big-r81** [comment] 2022-11-01 07:05
Closing wil close this for now, @sergey-safarov if you have a reproducible test case, please re-open this issue.

**Closed by big-r81** 2022-11-01 07:05 UTC
Labels: bug, waiting on user, needs-triage

**Comment by sergey-safarov** [comment] 2023-06-30 09:02
Sorry for the long delay
I have reproduced the issue.
In my installation, I have 3  node cluster that works IPv6 only (on the server no IPv4 address on the network interface card).
But when I try to replicate the database from another server I can see "A" DNS requests.
To start replications on my filesystem created `/tmp/json.txt` with content
```
{
  "source": {
    "headers": {},
    "url": "http://admin:pass@example.com:5984/alerts"
  },
  "target": {
    "headers": {},
    "url": "http://admin:pass@127.0.0.1:5984/alerts"
  },
  "continuous": false,
  "create_target": false
}
```
And then use curl command to start replication
```
curl -s -S \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json, text/javascript' \
  --data-binary @/tmp/json.txt \
  http://admin:pass@127.0.0.1:5984/_replicate
```
and in the response has
```
{"error":"replication_auth_error","reason":"{session_request_failed,\"http://source.local:5984/_session\",\"admin\",\n                        {conn_failed,{error,nxdomain}}}"}
```
Tested on 2.3.1 and will recheck on the latest docker image

**Comment by sergey-safarov** [comment] 2023-07-07 09:31
I have reproduced the issue on `apache/couchdb:3.3.2` docker image.

I tarted replicaation using json
```json
{
  "user_ctx": {
    "name": "admin",
    "roles": [
      "_admin",
      "_reader",
      "_writer"
    ]
  },
  "source": {
    "url": "http://ippbx-1a.la.example.com:5984/mydb",
    "headers": {
      "Authorization": "Basic XXXXXXXXXXXX"
    }
  },
  "target": {
    "url": "http://127.0.0.1:5984/mydb",
    "headers": {
      "Authorization": "Basic XXXXXXXXX"
    }
  },
  "create_target": true,
  "continuous": false
}
```
in the CouchDB output I see

> Jul 07 09:21:51 ippbx-1b.la.example.com docker[3677369]: [error] 2023-07-07T09:21:51.599467Z couchdb@ippbx-1b.la.example.com <0.6095.0> -------- couch_replicator_httpc: auth plugin initialization failed "http://ippbx-1a.la.example.com:5984/mydb/" {session_request_failed,"http://ippbx-1a.la.example.com:5984/_session","admin",{conn_failed,{error,nxdomain}}}
Jul 07 09:21:51 ippbx-1b.la.example.com docker[3677369]: [error] 2023-07-07T09:21:51.599676Z couchdb@ippbx-1b.la.example.com <0.6095.0> -------- throw:{replication_auth_error,{session_request_failed,"http://ippbx-1a.la.example.com:5984/_session","admin",{conn_failed,{error,nxdomain}}}}: Replication 69411eb9179c970995746a1ecd781fac+create_target failed to start "http://ippbx-1a.la.example.com:5984/mydb/" -> "http://127.0.0.1:5984/mydb/" doc <<"shards/00000000-7fffffff/_replicator.1688721035">>:<<"477deb9261a9927a1d20e90f2a001b31">> stack:[{couch_replicator_httpc,setup,1,[{file,"src/couch_replicator_httpc.erl"},{line,62}]},{couch_replicator_api_wrap,db_open,3,[{file,"src/couch_replicator_api_wrap.erl"},{line,68}]}]

And the tcpdump output
```
09:23:15.476762 IP 127.0.0.1.56494 > 127.0.0.1.domain: 63155+ A? ippbx-1a.la.example.com. (40)
09:23:15.476905 IP 127.0.0.1.domain > 127.0.0.1.56494: 63155* 0/1/0 (140)
09:23:15.476996 IP 127.0.0.1.55970 > 127.0.0.1.domain: 52657+ A? ippbx-1a.la.example.com. (40)
09:23:15.477078 IP 127.0.0.1.domain > 127.0.0.1.55970: 52657* 0/1/0 (140)
```
In the vm.args
```
[centos@ippbx-1b ~]$ grep proto_dist /opt/couchdb/etc/vm.args
-proto_dist inet6_tcp
```

**Comment by sergey-safarov** [comment] 2023-07-08 15:05
Issue recreated at https://github.com/apache/couchdb/issues/4668
