### ISSUE TITLE
all permission on DB will disappear when add the userLogin on permission(admins+members)

### ISSUE THREAD

**Issue by mohshraim** [apache/couchdb#850] opened 2017-09-28 23:30 UTC
all permission on DB will disappear when add userLogin on permission(admins+members)

## Steps to Reproduce (for bugs)
1.create a DB
2.go to permissions
3.add user login on admins list
4.add the same user login or any other login on members list
5.navigate to any other tab, then back to DB permissions,, all users will be deleted?

Note this working normally on version 2.0

## Your Environment
* Version used: 2.1
* Browser Name and version: chrome
* Operating System and version (desktop or mobile): all

**Comment by wohali** [comment] 2017-09-29 06:29
Duplicate of apache/couchdb-fauxton#929 which has been fixed.

**Closed by wohali** 2017-09-29 06:29 UTC

**Comment by clariontools** [comment] 2017-10-09 06:43
This has apparently been fixed, but how to get the fixed version?  I am currently using the CouchDB 2.1.0 apache/couchdb docker container, and not sure what approach to take to apply the Fauxton update?  The version that is part of the docker container reports  

So based on what I can see the code with the fix for this issue is [here](https://github.com/apache/couchdb-fauxton/commit/3bc13d09529d28abd9764fd8dce1f7b6f787e345) So I may just try and update my docker container with that because I understand the official apache/couch ‘convenience binary’ Docker images through Docker Hub is not updated that frequently.

**Comment by wohali** [comment] 2017-10-09 18:00
You can wait until CouchDB 2.1.1 is released, or you can build from sources. We don't officially support any other means of installation - though it may be possible.

**Comment by fne** [comment] 2021-11-25 08:27
Hello i m facing the same issue on couchdb version 2.3.1 with admin role
