### ISSUE TITLE
requires_valid_user default should be true

### ISSUE THREAD

**Issue by rjsteinert** [apache/couchdb#1917] opened 2019-02-13 09:53 UTC
## Description
When new users to CouchDB spin up CouchDB, they add their first admin user (maybe) and then assume they have secured their CouchDB installation.

## Steps to Reproduce
Tell someone new to CouchDB to spin it up and secure it. They'll add an admin user, then start creating databases and putting data in them before they read how database level security works because they assume their admin user only has access.

## Expected Behaviour
New users expect CouchDB to be secure by default.

## Additional context
- https://www.pcworld.com/article/3159527/security/attackers-start-wiping-data-from-couchdb-and-hadoop-databases.html
- Others?

**Comment by wohali** [comment] 2019-02-13 19:40
HI @rjsteinert ,

This would be a backward-incompatible change. As such it's already on our roadmap, a duplicate of https://github.com/apache/couchdb/issues/1504 and likely to occur with CouchDB 3.0.

Thanks for the note - we certainly haven't forgotten about this!

**Closed by wohali** 2019-02-13 19:40 UTC
Labels: duplicate, enhancement

**Comment by rjsteinert** [comment] 2019-02-13 20:39
That's fantastic! Thanks @wohali.

**Comment by rjsteinert** [comment] 2019-02-13 20:45
Would the CouchDB team be open to maybe some Fauxton UX improvements for the time being? "closed by default" as a mission for v3 makes sense as a long term goal, for now we could make sure that Fauxton makes it very clear that v2 is "open by default".

**Comment by wohali** [comment] 2019-02-13 22:02
@rjsteinert If you have specific suggestions, don't hesitate to place them over at https://github.com/apache/couchdb-fauxton/issues , where that team will be able to respond more directly.
