### ISSUE TITLE
Users Public Information {"error":"unauthorized","reason":"You are not authorized to access this db."}

### ISSUE THREAD

**Issue by hamiltonsalazar** [apache/couchdb#2908] opened 2020-05-27 02:53 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I followed the instructions in the documentation for [Users Public Information](https://docs.couchdb.org/en/stable/intro/security.html#users-public-information), but that don't work for me.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Current Behavior

I shared the field "name". I set up the `public_fields` configuration option with the next command: 

> curl -X PUT http://localhost:5984/_node/nonode@nohost/_config/couch_httpd_auth/public_fields \
   -H "Content-Type: application/json" \
   -d '"name"' \
   -u admin

I modified this for using in Windows with mi user "epi": 

> `curl -X PUT http://localhost:5984/_node/couchdb@localhost/_config/couch_httpd_auth/public_fields -H "Content-Type: application/json" -d "\"name\"" -u epi`

But when i check Jan’s document, CouchDB will respond with:

`{"error":"unauthorized","reason":"You are not authorized to access this db."}`

I have a user "jan" created in my database _users as can see below: 
![image](https://user-images.githubusercontent.com/36459473/82972022-ac6f2800-9f99-11ea-9b40-f2ba8e8f1c46.png)

Also i have "name" in the `public_fields` configuration option.
![image](https://user-images.githubusercontent.com/36459473/82972364-77afa080-9f9a-11ea-81d9-d6b187866950.png)

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
When i request a user document with the command: 

> curl http://localhost:5984/_users/org.couchdb.user:jan

CouchDB will respond with:  

`{"_id":"org.couchdb.user:jan","_rev":"2-724d8f9af35639db6d96504acda22a25","name":"jan"}`

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.1.0 
* Operating system and version: Windows 10 Pro 1909

**Comment by wohali** [comment] 2020-05-27 05:07
This is probably a duplicate of #2881 .

If it's not, please comment and we can reopen.

**Closed by wohali** 2020-05-27 05:07 UTC
Labels: bug, needs-triage

**Comment by hamiltonsalazar** [comment] 2020-05-27 05:40
In this case i want to see public infomation of that user.

I followed the instructions in the documentation for [Users Public Information](https://docs.couchdb.org/en/stable/intro/security.html#users-public-information), I shared the field "name". I set up the public_fields configuration option. I should be able to view this information from this user as the documentation shows:

`{"_id":"org.couchdb.user:jan","_rev":"2-724d8f9af35639db6d96504acda22a25","name":"jan"}`

Issue [#1881](https://github.com/apache/couchdb/issues/2881) doesn't change `public_fields` in `http: // localhost: 5984 / _node / nonode @ nohost / _config / couch_httpd_auth / public_fields`

**Comment by wohali** [comment] 2020-05-27 06:03
Did you do [this first](https://github.com/apache/couchdb/issues/2730#issuecomment-606741710)?

**Comment by hamiltonsalazar** [comment] 2020-05-27 18:39
@wohali  Thank you for help me, your time is important. It would be helpful if that is included in the oficial documentation. These changes are very relevant and users like me who we are learning about CouchDB from oficial documentation we can get confused.

**Comment by wohali** [comment] 2020-05-27 20:18
@hamiltonsalazar Yup, we are tracking that here: https://github.com/apache/couchdb-documentation/issues/513

**Comment by saurabhprasadsah** [comment] 2021-11-25 13:47
{"error":"unauthorized","reason":"You are not authorized to access this db."}..but authorisation will be correct

**Comment by Wildanzr** [comment] 2023-03-18 13:45
in my case this happened when there is no query activities for several minutes. Is there any session implemented?
