### ISSUE TITLE
Increase slack_db min priority (was: Upgrade from 2.3.1 to 3.1.0 - leads to 100% CPU Usage on both CentOs 7 and Mac-os)

### ISSUE THREAD

**Issue by ngspinu** [apache/couchdb#3047] opened 2020-07-29 20:18 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Hi there We have recently upgraded one of our production environments to 3.1.0. Prior to that we've had the same issue while running couchdb 3.1.0 on a Mac-os machine.
Basically what happens is: as soon you start couch and access some data it starts indexing(see attached fauxton screenshot) 
![image](https://user-images.githubusercontent.com/35466661/88848346-03d78180-d1f1-11ea-9f06-e0a2f027189d.png) and never stops consuming 100% of the CPU.
While doing some reading out there, we found out that deleting old(2.*) .compact files would make things chill down - but actually this was not the case. 
We ended up setting `autoupdate: false` to all our _design/docs. However, we are looking for a real fix to this one. Anybody can give a hand?

## Steps to Reproduce
1. Upgrade couch from 2.3.1 to 3.1.0
2. Start couch 
3. Access some view

## Your Environment
Mac-os, and Cent-os7
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.1.0
* Browser name and version:
* Operating system and version:

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by rjharmon** [comment] 2020-07-29 20:27
I'm guessing you may have many design docs that aren't being actively used by your application, and the autoupdate traffic on those is causing the undesired load?  Maybe some of them are simply obsolete?

Did you consider setting autoupdate: true on one design-doc at a time, for those design docs whose indexes you KNOW are going to be taking traffic?  The intent of the autoupdate behavior, as I understand it, is to shift indexing workload away from time-of-need and to execute it earlier - so it's ready when your application does a query.

Administratively, setting autoupdate: true gradually for all your less-used indexes, and removing any obsolete design docs, could get you caught up and cleaned up.

**Comment by ngspinu** [comment] 2020-07-29 20:43
@rjharmon thanks for hints. We have indeed removed all outdated/obsolete index and also compacted the views. We have quite a few views that are required so that the app can work, so whatever we would be doing - we still endup with a bunch of non-stop indexing views, that will eventually take our whole CPU. 

As for `autoupdate: true` - that is indeed used to keep the indexes warm, but I reckon.. there must be a middle way to keep things in line: IE: No 100%

**Comment by wohali** [comment] 2020-07-30 01:45
Check your thresholds for smoosh. 

https://docs.couchdb.org/en/latest/maintenance/compaction.html#channels

Probably it's the default config for the slack channel(s), which enqueues a db or view for compaction if the difference between actual and file size is > 16MB. This is too small for larger databases. The ratio channel uses a value of 2.0 and this is usually fine on its own.

Try increase the value by a few factors of two.

**Comment by wohali** [comment] 2020-07-30 01:46
@rnewson This has come up here and in #3047. I think we should change the default. What do you think?

**Comment by ngspinu** [comment] 2020-08-03 07:52
@wohali We have tried your suggestion IE: Increasing the 16MB to way more as our dbs are pretty big: ~1GB. Ratio too.
Is there anything else we can try? We have around 35 environments that we need to upgrade to 3.* and we can't do it until we understand what is causing the continuous indexing/unorthodox CPU consumption.

**Comment by wohali** [comment] 2020-08-03 11:01
Increase them more. If all you're seeing is forever running db and view compactions, smoosh is still being triggered too fast. Use the output of `GET /{db}` to determine the appropriate ratio for your needs. Or you can just disable certain DBs if they cause you trouble.

If what you're seeing is index _builds_ (not compactions) then `ken` is your issue, and you'll need to use configs to disable ken from building all your views. That's also explained in the documentation.

**Comment by bdoyle0182** [comment] 2020-12-03 00:59
I'm a little confused on what gets shipped by default. So you have the ratio channel and the slack channel. Are they both used by default or is one prioritized? If the slack default is 16mb, when would the ratio channel ever even get used? I think this should change it's pretty scary for people upgrading from 2.x and most people have much larger db's than this so they're treated to constant compaction

**Comment by molecular** [comment] 2021-03-21 09:01
I ran into this (100% cpu 1-2 minutes after couchdb start). It was a view compaction being constantly triggered on a ~5 million document db that gets new document(s) every 10 seconds.

I copied the defaults from https://docs.couchdb.org/en/latest/maintenance/compaction.html#channel-configuration and that resulted in much less frequent view compaction being triggered. 

So those "defaults2 are likely not the defaults on my system (archlinux, couchdb 3.1.1-2)

I also learned how to interpret db metadata to evaluate what's a good treshold priority

```sh
curl -s -u admin:<pw> -X GET http://blackbox:5984/solar | jq '(.sizes.file - .sizes.active) / 1E6'
```

**Comment by seigel** [comment] 2021-06-03 18:46
Any updates on this topic, just wondering if for @molecular or the author @ngspinu , if this ever resolved?

Thanks

**Comment by wohali** [comment] 2021-06-03 22:36
We're going to bump the slack_dbs/slack_views values to 512MB, but leave the ratio at 2.0. If people have evidence to suggest other appropriate defaults, let us know. The problem is that any setting here will be too aggressive for some users, and too lenient for others.

A potential future smoosh 2.0 could autotune in response to remaining disk space and current foreground load. 

A potential future smooth 3.0 would simply calculate the future state of the universe and then change these values to avoid any bad outcomes.

Towards either improvement... "pull requests welcome."

**Comment by nickva** [comment] 2022-10-24 19:32
Closing as fixed in https://github.com/apache/couchdb/issues/3047#issuecomment-854230247

**Closed by nickva** 2022-10-24 19:32 UTC

**Comment by molecular** [comment] 2022-11-08 08:49
@seigel has this ever resolved for me?

Yeah, kind of. I tune based on observing:

```sh
curl -s -u admin2:<pw> -X GET http://blackbox:5984/<db> | jq '{ slack: (.sizes.file - .sizes.active), slack_mb: ((.sizes.file - .sizes.active) / 1E6), ratio: (.sizes.file / .sizes.active) }'
```

I'm still a bit confused which rules are used and I think the parameter names are misleadning (especially 'priority' should be 'treshold' or something). I'm also confused like @bdoyle0182 as to wether ratio or slack or both channels are used as triggers when both are specified (like in `view_channels = upgrade_views,ratio_views,slack_views`.

**Comment by nickva** [comment] 2022-11-13 03:54
@molecular this issue might be interesting https://github.com/apache/couchdb/issues/4263

There is a fix that would hopefully go into the upcoming 3.3 release linked to the issue.

> wether ratio or slack or both channels are used as triggers when both are specified (like in view_channels = upgrade_views,ratio_views,slack_views.

The first channel which matches (for which we calculate a priority > 0) will enqueue the shard for compaction. So ratio would attempt first, and if that matches, it will enqueue the shard and matching stops. If ratio channel doesn't enqueue it, then slack channel will calculate priority and it may be enqueued there.

**Comment by molecular** [comment] 2022-11-21 08:27
> @molecular this issue might be interesting #4263

This makes a lot of sense. However doesn't affect me since I don't delete or update documents, only create.

Thanks for the clarification on ratio/slack triggering.

**Comment by nickva** [comment] 2022-11-21 19:05
> This makes a lot of sense. However doesn't affect me since I don't delete or update documents, only create.

That makes sense. If it's just newly created documents with no updates or deletions, then this wouldn't affect your use case.
