### ISSUE TITLE
Cluster to single node replication prints "Could not parse cookie from response headers cookie_format_invalid"

### ISSUE THREAD

**Issue by m90** [apache/couchdb#2369] opened 2019-12-17 13:20 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We are running a CouchDB cluster of 9 nodes. For backup purposes et. al. we would like to replicate all of its databases to a standalone single node CouchDB instance. The replication is a push-replication, i.e. the cluster has multiple continuous replications set up that target the single node.

Both the cluster and the single node are protected, so the replication knows about BasicAuth credentials for accessing the target as well as the source. We can use this setup to replicate data as expected and will see changes to the cluster being reflected in the backup node instantly.

Yet, for reasons unclear to us, all of the nodes in the cluster will log a message like this on each request made to the replication target:

```
[error] 2019-12-17T12:43:59.736014Z couchdb@couchdb2.local <0.24235.3> -------- couch_replicator_auth_session : Could not parse cookie from response headers cookie_format_invalid
```
Log output for the single node looks unsuspicious.

From what I understand, the replication should use the Authentication header defined in the replication docs and no HTTP cookies are involved, yet after digging through the codebase it looks like the second branch is hit here: https://github.com/apache/couchdb/blob/1347806d2feebce53325070b475f9e211d240ddf/src/couch_replicator/src/couch_replicator_auth_session.erl#L307-L312 when i would expect it to hit the above one saying `cookie_not_found`.

I'm not entirely sure if this expected, or if there is something going wrong in how we have set things up.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.1
* Browser name and version: n/a
* Operating System and version: Ubuntu 16 running CouchDB in Docker

Both the cluster as well as the single node are behind NGINX using the following proxy settings:

```
  location / {
    proxy_pass http://couchdb:5984;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

As far as I understand this should not add or remove any cookie related headers.

All of the nodes in the cluster share the same `couchdb.uuid` and `couch_httpd_auth.secret` when the single node has different values.

`chttpd.authentication_handlers` is not set / using the default value. Explicitly defining this to be basic auth only seemed to make no difference.

**Comment by seigel** [comment] 2020-01-10 21:15
Working from memory, bear with me.  Is there a security cookie defined some where in configs somewhere?  If so, and you edited it, does it have any spaces in it?

**Comment by kocolosk** [comment] 2020-01-10 22:13
Hi @m90 , thanks for this nicely detailed issue. As of #1462 (which landed in 2.2.0) the replicator will actually try to establish a session using cookie authentication. We made this change so that admins could crank up the work factor on authentication to protect against brute force attacks. So that explains why we're even talking about cookie-related code paths. The replicator will fall back to regular basic auth if it can't establish a session, so it makes sense that you're still seeing progress.

As far as why the CouchDB 2.3.1 replicator thinks the cookie it's receiving from the target instance is invalid ... that I'm not so sure about. Is the single node target instance also running 2.3.1?

If the log spam is getting to you and you just want the replicator to use basic auth you can change the `[replicator] auth_plugins` config setting on the cluster nodes:

```
[replicator]
auth_plugins = couch_replicator_auth_noop
```

See http://docs.couchdb.org/en/stable/config/replicator.html#replicator/auth_plugins for the config documentation.

/cc @nickva

**Comment by nickva** [comment] 2020-01-11 07:47
@m90 

If the error is `cookie_format_invalid` it seems like we got a cookie but it doesn't have the 'AuthSession=...` value in it.

https://github.com/apache/couchdb/blob/1347806d2feebce53325070b475f9e211d240ddf/src/couch_replicator/src/couch_replicator_auth_session.erl#L462-L464

Perhaps the proxy is adding another cookie and we end up parsing that one first. Or it's modifying CouchDB's cookie and we don't parse it correctly.

Would you be able to capture the headers and see what it looks like. Otherwise, to help reproduce the issue maybe paste your nginx.conf and I'll try it on my laptop.

In the meantime, good advice from @kocolosk regarding disabling the plugin, see if that helps while we figure out the issue.

@seigel, I do recall an issue related to that, good call

**Comment by m90** [comment] 2020-01-13 10:27
Thanks for the detailed reponse @nickva @kocolosk 

This is what I could find out using your info:

- When I disable the session auth plugin and use `couch_replicator_auth_noop` the log messages go away, replication continues working
- When I have nginx log the cookies included in the request(s), I can see that a non-empty `AuthSession` is being included in requests coming from the CouchDB Replicator. Its value also does not contain whitespace or anything unexpected.

---

For me to debug further, it would be interesting to know how I can further map these error messages to a request.

If I look at the log messages I can see some identifiers like:

```
[notice] 2020-01-13T09:35:41.390874Z couchdb@couchdb6.local <0.6072.1500> ce9077a0e1 some.hostname.example.com ...
```

or

```
[error] 2020-01-13T09:24:07.152363Z couchdb@couchdb7.local <0.8946.1807> -------- couch_replicator_auth_session : Could not parse cookie from response headers cookie_format_invalid
```

but I'm not entirely sure what the `0.6072.1500` (or similar) and `ce9077a0e1` are all about?

**Comment by kocolosk** [comment] 2020-01-13 15:40
The `0.6072.1500` is an Erlang process identifier. It won't be helpful for mapping log messages to requests, but Is occasionally helpful for understanding that several messages were emitted from the same internal process.

The `ce9077a0e1` is a unique identifier for the HTTP request and is included as the value of the `x-couch-request-id` header in the response generated by CouchDB.

**Comment by m90** [comment] 2020-01-13 15:48
> The ce9077a0e1 is a unique identifier for the HTTP request and is included as the value of the x-couch-request-id header in the response generated by CouchDB.

As the error messages print `--------` for this value, I assume I cannot really tell which request caused the error, right?

**Comment by kocolosk** [comment] 2020-01-13 15:52
Correct.

**Comment by nickva** [comment] 2020-01-13 19:48
@m90 

1) Could you capture the responses from the client to the proxy, then from the proxy to CouchDB see anything is adding cookie. Based on where the log is emitted, it not might not be an CouchDB cookie. https://github.com/apache/couchdb/issues/2369#issuecomment-573292483 . Also notice if there are any differences at all between "Set-Cookie" headers before and after the proxy.

2) Just to debug the scenario, can you eliminate the nginx proxy from the connection chain altogether, by say having a local cluster or use an SSH tunnel. Then see if errors persist or not.

Based on the logic in the code https://github.com/apache/couchdb/blob/1347806d2feebce53325070b475f9e211d240ddf/src/couch_replicator/src/couch_replicator_auth_session.erl#L462-L464 it looks like there was a cookie found _but_ it doesn't have an "AuthSession" part. That looks like a bug as CouchDB should ignore that cookie altogether and only pay attention to the ones having an "AuthSession" instead of failing nosily. However before making that change, let's see if we can confirm that theory.

**Comment by nickva** [comment] 2020-01-14 16:58
@m90 

I couldn't reproduce the issue on Ubuntu 18.04 with distro default nginx version and a with this config:

```
# Default server configuration
#
server {
listen 80 default_server;
listen [::]:80 default_server;

root /var/www/html;
index index.html index.htm index.nginx-debian.html;

server_name _;
        location / {
            proxy_pass http://localhost:15984;
            proxy_redirect off;
            #proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }
}
```

I had noticed in the code we would emit that error if we somehow got some other, non-CouchDB emitted cookie. So made PR to ignore those:

https://github.com/apache/couchdb/pull/2454

Also noticed the issue @seigel mentioned that we did not parse some of the cookie bits like expiration time properly. That field is not used, as we use max-age, but does indicate that if nginx somehow re-writes the cookie in a certain way the same parsing error might trigger in a different way and the cookie would not be found anymore. The parsing issue should be fixed in https://github.com/apache/couchdb/pull/2452 with the new web server component update.

Thought I am still curios, if you get a chance to capture the traffic between client and proxy and proxy and CouchDB as to what was causing the issue in your case. Another way to do it is to re-build from source and add a few debug lines to this module:

```
-spec parse_cookie(list()) -> {ok, age(), string()} | {error, term()}.
  parse_cookie(Headers0) ->
+    couch_log:error("***** Headers0:~p", [Headers0]),
      Headers = mochiweb_headers:make(Headers0),
      case mochiweb_headers:get_value("Set-Cookie", Headers) of
          undefined ->
              {error, cookie_not_found};
          CookieHeader ->
              CookieKVs = mochiweb_cookies:parse_cookie(CookieHeader),
+            couch_log:error("****CookieKVs:~p", [CookieKVs]),
              CaseInsKVs = mochiweb_headers:make(CookieKVs),
+            couch_log:error("-----> AuthSession:~p", [
```

**Comment by m90** [comment] 2020-01-15 09:27
I digged into the issue further in our setup ad it's starting to get very mysterious:

- removing the nginx proxy from our setup didn't make any difference
- cookie headers are not mangled in any way, everything looks as expected

---

Now to the weird part: I removed all of the replications (we replicate around 10 databases to their backups, authentication is done using BasicAuth) we have and then re-enabled them one by one. Doing this I found out the error occurs on a single database only. Let's call it the dubious database for now. Important to know is that __replication to the remote target works just fine for this database__.

If I replicate this dubious database to a different, still empty remote database, the error message will show up again. If I replicate the dubious database to a new local database and then replicate this copy to the remote, the error message does not show up. This makes me think the cause of this is bound to the database itself, but then again, it doesn't make much sense considering how that error might show up. 

Some more things I found out about the dubious database:
- The database's `_security` doc looks ok.
- It has a very high number of deleted docs compared to the other databases
- when I GET /dbs I can see that the database's revision number is unusually high compared to the other databases

I'm sorry if this does not make any sense at all (at least to me), but maybe one of you can make sense of this. Let me know if I can supply some additional info about the dubious database.

**Comment by wohali** [comment] 2020-01-15 20:35
Does that particular database have any VDUs (`validate_doc_update` functions) that might be affecting replication?

**Comment by nickva** [comment] 2020-01-16 01:00
@m90 

Ooh, very interesting. If it wasn't for just that one database, I would have guessed it's a case of the broken cookie parser https://github.com/apache/couchdb-mochiweb/commit/458eedf810b7417180a870077dbf957463adf08d. The fix is now on the master branch. But I think that would be triggered by any random database not just one specific one. Don't know if you could compile from the master branch and see if the problem shows up there.

**Comment by m90** [comment] 2020-02-04 10:09
Ok, we finally found out where this was coming from (although it still doesn't make too much sense): the Cluster that was causing the issues was (for reasons unknown to me) running behind a __Cloudflare Proxy__ which does some interesting and unexpected things to headers and such. Turning the proxy back off again made the log spam go away, just like I can reenable it by turning the proxy back on.

This still does not explain why it's a single database only, but it must be something in the combination of the two.

---

There is no `validate_doc_update` on the database.

**Comment by wohali** [comment] 2020-02-04 15:41
Would you be willing to share the name of the database? My guess is Cloudflare has some sort of rule that's kicking in due to the nature of the data it thinks is in place.

**Comment by m90** [comment] 2020-02-05 10:17
The database name sounds relatively unsuspicious (to me), it's `van-shipments`.

**Comment by wohali** [comment] 2020-03-13 23:08
For now I'm going to close this as not a bug - sounds like an interaction with CouchDB behind CloudFlare.

If you're able to get any more detailed info on what CloudFlare does to mangle the cookie, that'd be most appreciated. We can always reopen this if something obvious presents itself.

**Closed by wohali** 2020-03-13 23:08 UTC
Labels: bug, needs-triage
