### ISSUE TITLE
Protocol 'couch': not supported when following 3.2.0 TLS config instructions

### ISSUE THREAD

**Issue by weareu** [apache/couchdb#3821] opened 2021-11-07 17:59 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When configuring TLS based distribution as specified in new docs for Couch 3.2.0 we get an error on service start on Ubuntu that 'couch' distribution protocol is not supported. When reverting to our previous inet_tls config we had the error goes away. Is there such a protocol or is this a issue with the documentation?

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
Configure TLS distribution exactly as specified in documentation for 3.2.0 here: https://docs.couchdb.com/en/latest/cluster/tls_erlang_distribution.html

Under 4.6.2 in vm.args -
-proto_dist couch
-couch_dist no_tls \"clouseau@127.0.0.1\"
-ssl_dist_optfile xxx

Once configured start CouchDB. Get error from journal, no log is created.

Nov 07 09:08:58 xxx systemd[1]: Started Apache CouchDB.
Nov 07 09:08:59 xxx couchdb[20462]: 2021-11-07 09:08:59 application_controller: ~ts: ~ts~n
Nov 07 09:08:59 xxx couchdb[20462]:         ["syntax error before: ","'*'"]
Nov 07 09:08:59 xxx couchdb[20462]:         "*@127.0.0.1"
Nov 07 09:08:59 xxx couchdb[20462]: Protocol 'couch': not supported
Nov 07 09:08:59 xxx systemd[1]: couchdb.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 09:08:59 xxx systemd[1]: couchdb.service: Failed with result 'exit-code'.

Tried this on a few different servers in our dev environment clusters and on prod. All however have the same ubuntu version.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

Expect couchdb to start with TLS distribution. However I'm not sure if the documentation is wrong and setting should be -proto_dist inet_tls

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.2.0
* Browser name and version: N/A
* Operating system and version: Ubuntu 18.04.6 LTS (Bionic)

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jaydoane** [comment] 2021-12-02 22:25
> I'm not sure if the documentation is wrong and setting should be -proto_dist inet_tls

Based on [Erlang docs](https://www.erlang.org/doc/man/erl.html), this seems like the correct analysis.

**Comment by jaydoane** [comment] 2021-12-02 23:39
What exactly are you using in vm.args? The file that ships with CouchDB has these lines:
```
#-proto_dist couch
#-couch_dist no_tls \"clouseau@127.0.0.1\"
#-ssl_dist_optfile <path/to/couch_ssl_dist.conf>
```
which I assume you uncommented, and added an actual value for `ssl_dist_optfile`.

However, you report above the following:
```
-proto_dist couch
-couch_dist no_tls "clouseau@127.0.0.1"
-ssl_dist_optfile xxx
```
where `"clouseau@127.0.0.1"` does not contain backslashes.

The fun thing is that neither will work with recent versions of Erlang. What version are you using?

You will probably need to do something like
```
-couch_dist no_tls '"clouseau@127.0.0.1"'
-ssl_dist_optfile '"path/to/couch_ssl_dist.conf"'
```
note the single quotes wrapping the double quotes.

**Comment by jiahuili430** [comment] 2021-12-03 07:35
## Reproduce Error
I am not sure what the `xxx` in `-ssl_dist_optfile xxx` is, so I cannot reproduce the error.
Usually, we want to use the absolute path for configuration file `couch_ssl_dist.conf`.

## Why use `-proto_dist couch` instead of `-proto_dist inet_tls`?
If use `inet_tls`, all nodes will only use TLS. We cannot specify some nodes to use TLS and some nodes to use TCP.
TCP is needed for `clouseau@127.0.0.1`, which related to the [search feature](https://docs.couchdb.com/en/latest/ddocs/search.html?highlight=clouseau).

**My Environment:**
- CouchDB version used: 3.x
- Operating system and version: MacOS Monterey 12.0.1
- Erlang/OTP 23

## How to use `TLS Erlang Distribution`
There are two modes: local development and release.
The command to connect to the `remsh` is different.


### Local Development
1. Generate`erlserver.pem` and `couch_ssl_dist.conf` in `/dev/` folder
```
git clone https://github.com/apache/couchdb.git couchdb
cd couchdb/
git checkout 3.x
./configure --dev --generate-tls-dev-cert
```
2. Change `vm.args`
```
cd rel/overlay/etc/
vi vm.args
```
Uncomment the following parameters.
- Please use the absolute path of the couch_ssl_dist.conf file, for example: `/Users/<username>/couchdb/dev/couch_ssl_dist.conf`
```
-proto_dist couch
-couch_dist no_tls \"clouseau@127.0.0.1\"
-ssl_dist_optfile /Users/<username>/couchdb/dev/couch_ssl_dist.conf

## If we want to use TCP for node1 and TLS for node2 and node3, add the following parameters in `vm.args`.
-couch_dist no_tls \"node1@127.0.0.1\"
```
3. Compile and Run CouchDB
```
cd ../../../
make
./dev/run --admin=adm:pass 
```
4. Connect to Remsh to Verify

Open another terminal
```
cd couchdb
./dev/remsh
```
For node1's remsh (**TCP**), enter `net_kernel:nodes_info().`, you'll see the following information:
```
(**node1@127.0.0.1**)1> net_kernel:nodes_info().
{ok,[{'**node2@127.0.0.1**',
         [{owner,<0.876.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49423},"127.0.0.1",**tls**,inet}},
          {type,normal},
          {in,247},
          {out,279}]},
     {'**node3@127.0.0.1**',
         [{owner,<0.897.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49424},"127.0.0.1",**tls**,inet}},
          {type,normal},
          {in,246},
          {out,250}]},
     {'**remsh3451@127.0.0.1**',
         [{owner,<0.3956.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49495},"127.0.0.1",**tcp**,inet}},
          {type,hidden},
          {in,7},
          {out,13}]}]}
```
For node2's remsh (**TLS**):
Open another terminal, and type
```
cd couchdb
NODE=2 ./dev/remsh-tls
```
You'll see the following information:
```
(**node2@127.0.0.1**)1> net_kernel:nodes_info().
{ok,[{'**node1@127.0.0.1**',
         [{owner,<0.877.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49441},"127.0.0.1",**tls**,inet}},
          {type,normal},
          {in,286},
          {out,274}]},
     {'**node3@127.0.0.1**',
         [{owner,<0.934.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49424},"127.0.0.1",**tls**,inet}},
          {type,normal},
          {in,265},
          {out,331}]},
     {'**remsh3652@127.0.0.1**',
         [{owner,<0.9630.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49541},"127.0.0.1",**tls**,inet}},
          {type,hidden},
          {in,15},
          {out,22}]}]}
```


### For Release
1. Follow the same steps 1,2,3 for local development
```
git clone https://github.com/apache/couchdb.git couchdb
cd couchdb/
git checkout 3.x
./configure --dev --generate-tls-dev-cert

cd rel/overlay/etc/
vi vm.args
```
Uncomment the following parameters:
```
-proto_dist couch
-couch_dist no_tls \"clouseau@127.0.0.1\"
-ssl_dist_optfile /Users/<username>/couchdb/dev/couch_ssl_dist.conf
```
Compile CouchDB
```
cd ../../../
make
```
2. Build the release
```
make release
```
3. Add `adm = pass` in the `[admins] section of the `local.ini` file
```
cd rel/couchdb/etc
vi local.ini
```
4. Run CouchDB and Connect to Remsh to Verify
```
cd ../
./bin/couchdb
```
Open another terminal
```
cd couchdb/rel/couchdb/
./bin/remsh -t /Users/<username>/src/couchdb/dev/couch_ssl_dist.conf
```
If the node uses **TLS**:
```
(**couchdb@127.0.0.1**)1> net_kernel:nodes_info().
{ok,[{'remsh7166@127.0.0.1',
         [{owner,<0.2612.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},49937},"127.0.0.1",**tls**,inet}},
          {type,hidden},
          {in,10},
          {out,15}]}]}
```
If the node uses **TCP**:
Add `-couch_dist no_tls \"couchdb@127.0.0.1\"` to `couchdb/rel/couchdb/etc/vm.args`
Open another terminal, and type
```
cd couchdb/rel/couchdb
./bin/remsh
```
You'll see the following information:
```
(**couchdb@127.0.0.1**)1> net_kernel:nodes_info().
{ok,[{'remsh7345@127.0.0.1',
         [{owner,<0.578.0>},
          {state,up},
          {address,
              {net_address,{{127,0,0,1},50001},"127.0.0.1",**tcp**,inet}},
          {type,hidden},
          {in,10},
          {out,19}]}]}
```
## References

- Related PR: https://github.com/apache/couchdb/pull/3643
- CouchDB Documentation: https://docs.couchdb.com/en/latest/cluster/tls_erlang_distribution.html
- Using TLS for Erlang Distribution: https://www.erlang.org/doc/apps/ssl/ssl_distribution.html
- How to Implement an Alternative Carrier for the Erlang Distribution: https://www.erlang.org/doc/apps/erts/alt_dist.html#distribution-module

**Comment by nickva** [comment] 2021-12-03 22:30
@jiahuili430 Thanks for great instructions how to set everything up!

I was able to reproduce the issue:

```
apache-couchdb-3.2.1/rel/couchdb  % ./bin/couchdb
2021-12-03 16:25:10 application_controller: ~ts: ~ts~n
        ["syntax error before: ","'.'"]
        "clouseau@127.0.0.1"
Protocol 'couch': not supported
```

And just like @jaydoane mentioned this most likely happens because of the difference in parsing between Erlang versions. I used Erlang 20 to reproduce the issue.

It could be that we'd just document that unfortunately Erlang 20 doesn't work for this custom TLS module and only users who compile against Erlang 22 or so would be able to use this feature.

Unfortunately even `-ssl_dist_optfile '"path/to/couch_ssl_dist.conf"'` didn't seem to solve the issue.

**Comment by rnewson** [comment] 2021-12-04 09:37
hmmm but we (cloudant) had this running with erlang 19 (or earlier). is there a bug/issue from OTP around this apparent change to the parsing mechanism for vm.args?

**Comment by jaydoane** [comment] 2021-12-04 23:55
> hmmm but we (cloudant) had this running with erlang 19 (or earlier). is there a bug/issue from OTP around this apparent change to the parsing mechanism for vm.args?

Not definitive, but @chewbranca found this [parsing change in erlexec.c](https://github.com/erlang/otp/issues/3859) which seems to have been introduced in OTP 22.1

**Comment by nickva** [comment] 2021-12-06 23:03
I think there are two separate issues with Erlang 20 - the parsing issue found by @jaydoane and there was another API issue where the dist API had changed and we didn't account for the old version.

Made a PR to fix it https://github.com/apache/couchdb/pull/3863

**Comment by nickva** [comment] 2021-12-10 21:34
Since we merged the fix, closing the issue. 

As a work-around until the next release, try to use Erlang 23+ if possible.

**Closed by nickva** 2021-12-10 21:34 UTC
Labels: bug
