### ISSUE TITLE
Cannot compile of OTP20

### ISSUE THREAD

**Issue by drasko** [apache/couchdb#815] opened 2017-09-14 10:16 UTC
```bash
drasko@Marx:~/couchdb/apache-couchdb-2.1.0$ make
==> config (compile)
ERROR: OTP release 20 does not match required regex R16B03|R16B03-1|17|18|19
ERROR: compile failed while processing /home/drasko/couchdb/apache-couchdb-2.1.0/src/config: rebar_abort
Makefile:67: recipe for target 'couch' failed
make: *** [couch] Error 1
```

**Comment by wohali** [comment] 2017-09-14 15:55
Duplicate of #617.

**Closed by wohali** 2017-09-14 15:55 UTC
