### ISSUE TITLE
function_clause when replicator receives a 401 or 402

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2483] opened 2020-01-23 18:23 UTC
## Description

If incorrect authentication is entered into a replicator document, the replicator crashes with:

```
ChangesReader process died with reason: {function_clause,[{couch_replicator_api_wrap,'-changes_since/5-fun-2-',[401,[...
```

This should be cleaned up.

@willholley says "fwiw I've seen the same for 402 payment required errors which Cloudant sometimes sends."

## Steps to Reproduce

Enable require_valid_user_true, set up user accounts, then attempt to replicate with missing or invalid credentials.

## Expected Behaviour

Shouldn't result in a traceback in the logs.

## Your Environment

* CouchDB version used: 2.3.1
* Browser name and version: n/a
* Operating system and version: Linux x64

**Comment by mqtik** [comment] 2020-09-07 13:38
I don't see this as an issue.

If you want to replicate with invalid credentials (or logged out), you need to set the database as Public (go to Permissions under Fauxton). The error will be gone by then.

**Comment by wohali** [comment] 2020-09-07 18:26
For reference, we consider any `function_clause` in the logs as a bug.

Pull requests welcome.

**Comment by jiahuili430** [comment] 2021-05-05 20:36
# I can't reproduce the issue
I have tried to use CouchDB with plugin session, and without auth_plugins(auth_plugins = couch_replicator_auth_noop), but none of them can reproduce the problem.
# Reproduce Steps
## 1. CouchDB with plugin session:
Compile and run CouchDB 3.x locally
```
make && ./dev/run --admin=adm:pass -n1
```
Set require_valid_user to true
```
curl -XPUT $DB/_node/_local/_config/chttpd/require_valid_user -d '"true"'
```
Replicate with invalid credentials, but there is no **"function_clause"** in the log.
```
curl -XPOST "$DB/_replicate"  \
  -H 'Content-Type:application/json' \
  -d "{\"source\": \"$DB/alice-db\", \"target\": \"http://adm:wrongpass@localhost:15984/alice-db-replicate\", \"create_target\": true }"

{"error":"unauthorized","reason":"unauthorized to access or create database http://adm:*****@localhost:15984/alice-db-replicate/"}
```
## 2. CouchDB without auth_plugins:
Set **auth_plugins = couch_replicator_auth_noop** in the "default.ini" file, and the follow the previous commands, but still cannot find **"function_clause"** in the log.
# Environment
- CouchDB version used: 3.x
- Operating system and version: MacOS Big Sur 11.3.1

**Comment by nickva** [comment] 2021-07-15 16:58
Thanks for trying it out @jiahuili430

I think we can close it as reproduce-able the latest release. If we get more details steps or  something we missed in our setup we can re-open it.

**Closed by nickva** 2021-07-15 16:58 UTC
Labels: bug
