### ISSUE TITLE
couchdb latest rev (2.2.1?) Runaway "127.0.0.1 refused to connect." error on Mac OS 11

### ISSUE THREAD

**Issue by rperretta** [apache/couchdb#1040] opened 2017-12-03 21:16 UTC
I downloaded and installed the latest rev. from .dmg on or about 12/1/17.

For reference, please note that I have a fair amount of Couchdb experience from recent employment. Not a superstar but functional.

Couchdb installed and ran but did not pass "Verify" tripping up on the last item in the list. I'm running OS X 10.11.6.

After that, every attempt to open Couchdb results in the "127.0.0.1 refused to connect." error. At this point, the Couchdb daemon (I presume) repeatedly attempts to open tabs with the same result. It continues to open tab after tab until I attempt to shutdown the computer. This is tricky because Couchdb causes the browser to cancel shutdown as it opens tabs every few seconds.  You can kill processes in the Terminal or get lucky on your Cmd-Q timing and get between them.  If Cmd-Q isn't immediately followed by shutdown, Couchdb will restart the browser and again, prevent shutdown.

This happens with Chrome, Blisk and Safari. There is no other behavior than this when attempting to run Couchdb.

I believe I've provided all the details but am of course happy to assist. Thanks for your attention in this matter.

**Comment by rperretta** [comment] 2017-12-03 21:21
A correction. That's Mac OS 10. Sorry about any confusion.

**Comment by rperretta** [comment] 2017-12-04 02:22
Ran Onyx scripts on system, dumped Couchdb into app cleaner - didn't have time to remove files individually, reinstalled and reran. No luck. Went back to Couchdb 1.6.1.  Works fine, passes verification.

**Comment by wohali** [comment] 2018-01-16 20:12
I believe this is a duplicate of #979. Try running `brew install nspr`. If that fixes it, it's the same problem. If not, please reopen this ticket.

**Closed by wohali** 2018-01-16 20:12 UTC
Labels: macos
