### ISSUE TITLE
can not install couchdb under centos 7

### ISSUE THREAD

**Issue by hanbi918** [apache/couchdb#1420] opened 2018-07-01 08:40 UTC
when i install couchdb refer to this doc: http://docs.couchdb.org/en/2.1.1/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages, i get following error:
```====================================================================================================
 Package        Arch          Version                      Repository                          Size
====================================================================================================
Installing:
 couchdb        x86_64        2.1.1-2.el7.centos           bintray--apache-couchdb-rpm         18 M

Transaction Summary
====================================================================================================
Install  1 Package

Total download size: 18 M
Installed size: 39 M
Is this ok [y/d/N]: y
Downloading packages:
couchdb-2.1.1-2.el7.centos.x86 FAILED                                           14 MB  00:00:00 ETA
http://apache.bintray.com/couchdb-rpm/el7/x86_64/couchdb-2.1.1-2.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=bintray--apache-couchdb-rpm clean metadata
Trying other mirror.


Error downloading packages:
  couchdb-2.1.1-2.el7.centos.x86_64: [Errno 256] No more mirrors to try.
```

anybody can help me solve this problem!
thanks!

**Comment by wohali** [comment] 2018-07-02 02:50
Known issue and will be resolved with the next release of Apache CouchDB. Sorry for the inconvenience.

This is effectively a duplicate of #1293

**Closed by wohali** 2018-07-02 02:50 UTC
