### ISSUE TITLE
Make couchdb 2 cross compile friendly

### ISSUE THREAD

**Issue by Schoumi** [apache/couchdb#727] opened 2017-07-31 13:11 UTC
Couchdb can't be cross-compile at this time (or haven't found the way to do so) and this is very unfortunate. It make not simple or impossible to build package for another architecture. 
If couchdb can be cross-compiled right now, can you tell me how to do or a link to a documentation to do that.

## Expected Behavior
./configure should handle --host --build --prefix options
make should use LDFLAGS and other standard flag than override them in rebar files.

## Context
Build package to another processor architecture than the one i run in order to build package on a system to run for another unable to build for it's own easily

## Your Environment
* Version used: 2.0.0
* Operating System and version (desktop or mobile): Linux Desktop
* Target: Linux armv5

**Comment by wohali** [comment] 2017-07-31 15:02
This is basically a duplicate of #546.

**Closed by wohali** 2017-07-31 15:02 UTC
