### ISSUE TITLE
CouchDB 2 service keeps restarting on Windows Server 2016

### ISSUE THREAD

**Issue by callum-spartan** [apache/couchdb#698] opened 2017-07-19 16:09 UTC
I have installed CouchDB 2.0.0.2 on Windows Server 2016 and I am unable to access the address http://127.0.0.1:5984/_utils/ 

I have looked at the Apache CouchDB service and I could see that the status kept fluctuating between "Running" and "Starting"

I then stopped the service and tried to start CouchDB using couchdb.cmd and I received this error:

`{"Kernel pid terminated",application_controller,"{application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,httpd,eacces}}}},{couch_app,start,[normal,[]]}}}"}`

I have attached couchdb.log and erl_crash.dump here: [logs.zip](https://github.com/apache/couchdb/files/1159709/logs.zip)

CouchDB 1.6.1 was previously installed on this server without any issue. But now we have uninstalled 1.6.1 for the upgrade to CouchDB 2.0.0.2

Any suggestions on troubleshooting this issue?

## Environment
* Version used: CouchDB 2.0.0.2
* Operating System: Windows Server 2016

**Comment by wohali** [comment] 2017-07-19 16:47
The `eacces` in your logfile tells us the issue is file permissions for the user who runs the service. Can you try checking permissions on the `C:\CouchDB` directory (or wherever you installed it) and ensure the Local Service user has access to write to that directory?

I don't have a Windows Server 2016 machine to test on - will have to remedy that. I know for a fact it works under Windows 10 correctly.

**Comment by callum-spartan** [comment] 2017-07-21 08:22
Thank you for your response. 

I have added the Full Control permissions for the Local Service user to the C:/ CouchDb directory and all containing directories and files.

![directorypermissions](https://user-images.githubusercontent.com/12034732/28454979-19bf469e-6df5-11e7-8bbf-2c702f1ba91d.jpg)


I then restarted the service and unfortunately the problem still persists. 
Here is the latest log and crash dump: [LatestLogs.zip](https://github.com/apache/couchdb/files/1164886/LatestLogs.zip)

I can confirm that CouchDB 2.0.0.2 works on my Windows 10 development environment but not on this Windows Server 2016 environment.

Any other troubleshooting ideas are welcome.

**Comment by davisp** [comment] 2017-07-21 15:39
@callum-spartan Ah! I think that's actually a socket access error. Did you set the HTTP port to 80 and not allow it to bind? I haven't got a clue on windows specifics but on *nix you'd need to give the process administrator level privileges to bind to anything less than 1024.

**Comment by wohali** [comment] 2017-07-21 15:45
The specific error isn't file access errors, it's port access errors, my mistake, and thank you @davisp.

@callum-spartan Are you using Windows containers? This pointer might be the issue https://stackoverflow.com/questions/44817861/windows-container-port-binding-not-working-on-windows-server-2016-using-docker

I'll try and test this on my own, but if I can't reproduce...it's likely your local setup.

**Comment by callum-spartan** [comment] 2017-07-24 08:30
Thank you @davisp and @wohali.

I am not using Windows Containers in this environment.

Do you know how I can troubleshoot the port access problem further to see if it's my local setup?

**Comment by wohali** [comment] 2017-07-26 19:30
Hi @callum-spartan,

I have locally installed Windows Server 2016 Standard Edition with Desktop Experience, fully updated it from Windows Update, downloaded the CouchDB 2.0.0.2 x64 .msi file, and installed it. I am then able to access `http://localhost:5984/` using the built-in Internet Explorer 11 (after modifying IE's default security settings for the Local intranet to Low) and successfully get back the response `{"couchdb":"Welcome","version":"2.0.0","vendor":{"name":"The Apache Software Foundation"}}`. So Windows Server 2016, out of the box, runs the CouchDB 2.0.0.2 installer just fine. I then installed Firefox from https://getfirefox.com/ and was able to bring up `http://localhost:5984/_utils` just fine (we don't test for Fauxton compatibility with IE) and ran the Verify function. It succeeded with no errors.

I'm going to close this ticket out, as it is blocking our 2.1 release, but we can continue to try and work together to solve your problem here. My guess is that you still have another process running on the default port. Perhaps CouchDB 1.6.1 didn't uninstall correctly - what happens when you browse to http://localhost:5984/? Are you getting a response?

**Closed by wohali** 2017-07-26 19:30 UTC
Labels: windows

**Comment by callum-spartan** [comment] 2017-08-03 09:55
Thanks for your time @wohali.

I have successfully installed CouchDB 2.0.0.2 on to another instance of Windows Server 2016 so it must have been a problem with my environment.

Thanks again.

**Comment by callum-spartan** [comment] 2017-12-21 09:58
Hi @wohali 

I have just experienced the same problem after updating a Windows Server 2012 machine. 
It turned out that the Windows Remote Management service is also using port 5986.

Thanks.

**Comment by reyj007** [comment] 2018-02-22 17:31
callum-spartan - been searching high and low for resolving this issue. I was working w both 2012 & 2016 instances on GCP and could not get around the service starting, restarting until I saw your "Windows Remote Management " comment. That did it! Now to figure out what "Windows Remote Management" does?

**Comment by wohali** [comment] 2018-02-22 19:02
https://msdn.microsoft.com/en-us/library/aa384372(v=vs.85).aspx

```
WinRM 2.0:  The default HTTP port is 5985, and the default HTTPS port is 5986.
```

You can change the port to fix this problem if desired.

**Comment by reyj007** [comment] 2018-02-22 20:06
Thanks but CouchDB uses specifically 5984 so why the issue still? Also FYI, on AWS no issues whatsoever. Only GCP

 

Rey Jimenez

 <mailto:reyj@askrey.com> reyj@askrey.com

**Comment by wohali** [comment] 2018-02-22 21:15
CouchDB binds to both ports 5984 (clustered interface) and 5986 (localhost-only administrative interface).

**Comment by reyj007** [comment] 2018-02-22 22:23
Gotcha. Thanks for super quick reply
