### ISSUE TITLE
make fails on AArch64, Fedora 33

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [apache/couchdb#3273] opened 2020-11-17 09:22 UTC
==> config (compile)
ERROR: OTP release 23 does not match required regex 19|20|21|22
ERROR: compile failed while processing /data/jw/apache/couchdb/src/config: rebar_abort
make: *** [Makefile:122: couch] Error 1

**Comment by wohali** [comment] 2020-11-17 16:08
Duplicate of #3115 .

We don't at present recommend running CouchDB in production on Erlang 21+. (Our binaries all ship against 20.3.8.25.)

**Closed** 2020-11-17 16:08 UTC
Labels: duplicate
