### ISSUE TITLE
Creating simple View in _users Database fails with "unknown_error"

### ISSUE THREAD

**Issue by realulim** [apache/couchdb#982] opened 2017-11-11 15:04 UTC
## Expected Behavior
I am trying to create a view that returns all users by their email address. This worked in earlier versions (e. g. 2.1.0) with the steps detailed below.

## Current Behavior
The error message I am getting, when trying to create the view, is this:
{"error":"unknown_error","reason":"undef","ref":2998209829}

## Steps to Reproduce (for bugs)
0. cd /opt
1. mkdir tmp && cd tmp && wget http://mirror.synyx.de/apache/couchdb/source/2.1.1/apache-couchdb-2.1.1.tar.gz
2. tar -xzf apache-couchdb-2.1.1.tar.gz && cd apache-couchdb-2.1.1 && ./configure && make release
3. cp -R rel/couchdb /opt/ && find /opt/couchdb -type d -exec chmod 0770 {} \\; && chmod 0644 /opt/couchdb/etc/*
4. find /opt/couchdb -type d -exec chmod 0770 {} \\;
5. configure admin-password to be "admin" in local.ini
6. systemctl start couchdb (as root via the unit file as provided below)
7. verify CouchDB is running by curl -u admin:admin http://localhost:5984/_membership
8. curl -s -X PUT -u admin:admin http://localhost:5984/_users
9. curl -s -X PUT -u admin:admin http://localhost:5984/_replicator
10. curl -s -X PUT -u admin:admin http://localhost:5984/_global_changes
11. curl -s -u admin:admin -X PUT http://localhost:5984/_users/_design/User -d '@/home/couchpotato/User.json' (file User.json as provided below)

## Your Environment

* Version used: 2.1.1
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): CentOS Linux release 7.4.1708 (Core) 

couchdb.service:
[Unit]
Description=Apache CouchDB
Wants=network-online.target
After=network-online.target

[Service]
RuntimeDirectory=couchdb
User=couchpotato
Group=couchpotato
ExecStart=/opt/couchdb/bin/couchdb
Restart=always

[Install]
WantedBy=multi-user.target

User.json:
{
  "_id": "_design/User",
  "views": {
    "by_email": {
      "map": "function(doc) { if(doc.email) {emit(doc.email, doc._id)} }"
    }
  },
  "lists": {},
  "shows": {},
  "language": "javascript",
  "filters": {},
  "updates": {}
}

**Comment by bjonnh** [comment] 2017-12-05 00:07
I wasn't able to reproduce the bug using the docker image 2.1.1
(using both fauxton or direct curl access).

It would help if you removed all specific configuration that you made and tested again.

**Comment by vmx** [comment] 2017-12-05 00:08
So it looks like it's an environment issue. `undef` errors usually mean that some Erlang module can't be found.
I suggest that you look in the log files to see which module/function is "undef", this should help narrowing it down.

**Comment by realulim** [comment] 2017-12-05 07:44
Thanks guys for helping with this. As to the config, there is no configuration at all except step 5 as detailed above (setting the admin password). The config files for the reproducible case above are as downloaded from the official sources. Obviously, my actual system has lots of configuration, but I already trimmed it down for the reproducible case as detailed above.

There wasn't anything striking in the log, but I'll post the entries later as well as try to "git bisect" to find the commit between 2.1.0 and 2.1.1 that caused the error.

**Comment by realulim** [comment] 2017-12-05 10:59
Ok, here is the log entry:

[error] 2017-12-05T11:59:10.116706Z couchdb@127.0.0.1 <0.3495.0> f3b107961c req_err(2998209829) unknown_error : undef
    [<<"jiffy:decode/2">>,<<"couch_util:json_decode/1 L429">>,<<"chttpd_db:db_doc_req/3 L814">>,<<"chttpd:process_request/1 L295">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L239">>]
[notice] 2017-12-05T11:59:10.116907Z couchdb@127.0.0.1 <0.3495.0> f3b107961c localhost:5984 127.0.0.1 undefined PUT /_users/_design/User 500 ok 3

**Comment by realulim** [comment] 2017-12-05 12:31
I'm not sure what Jiffy is nor how to check its version, but I have installed this RPM: erlang-jiffy-0.8.5-3.el7.x86_64

**Comment by vmx** [comment] 2017-12-05 12:48
Try to get a version >= 0.14.12 and you should be good.

**Comment by realulim** [comment] 2017-12-05 14:23
Unfortunately there is no newer release for CentOS/EL7.

CouchDB 2.1.0 did work with this older version of Jiffy. Is there a definitive list of dependencies for CouchDB? Or perhaps test protocols / procedures for releases on supported platforms?

**Comment by vmx** [comment] 2017-12-05 14:43
@realulim Did you install the official RPM? It looks like it already contains Jiffy. Try to uninstall the Jiffy package, perhaps there's some problem with the paths.

**Comment by realulim** [comment] 2017-12-05 14:53
I installed from sources in order to customise the location of CouchDB and its shards in the filesystem. But now that you mentioned it, I tried to install the RPM from the official yum repo and that works! So apparently the dev team has a better build process than the one detailed in the docs :)

So I suppose this issue can be closed now or transformed into a documentation issue, whatever seems more appropriate. I can work with the binaries. Thanks all for your help, much appreciated!

**Comment by vmx** [comment] 2017-12-05 15:35
I could imagine that if you compile from source, that it picks up your system's Jiffy. So perhaps if works if you remove it and then do a source installation from scratch.

**Comment by realulim** [comment] 2017-12-05 17:33
No, the source installation already assumes that all erlang stuff etc. is installed. So I installed Jiffy (and all other deps) from the CentOS repository, which has no newer versions.

**Comment by vmx** [comment] 2017-12-05 19:32
It expects Erlang to be installed (also according to the documentation). But I don't think it expects Jiffy to be installed. Could you please try it again with Jiffy uninstalled (if it needs Jiffy installed, that would be a bug in the documentation).

**Comment by realulim** [comment] 2017-12-05 21:49
While I don't really get a decent couchdb installation up that way, I do get it running enough to confirm that the problem detailed in this issue doesn't appear, when not installing erlang-jiffy and relying on the CouchDB build to add it.

**Comment by vmx** [comment] 2017-12-05 22:50
Would you mind closing the issue if it is resolved?

**Closed** 2017-12-05 23:11 UTC
