### ISSUE TITLE
CouchDB 2.1.1 crashes and keeps restarting - macOS High Sierra 10.13.1

### ISSUE THREAD

**Issue by mr-bobz** [apache/couchdb#1015] opened 2017-11-24 03:33 UTC
Updated from macOS Sierra to High Sierra (10.13.1)

Reinstalled CouchDB to latest (2.1.1), downloaded from http://couchdb.apache.org/ 

## Current Behavior
Cannot connect to DB from app, but the following works:

> curl http://localhost:5984

`{"couchdb":"Welcome","version":"2.1.1","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}`

> http://127.0.0.1:5984/_utils/

Fauxton loads fine, but restart below _fails_

> curl http://localhost:5984/_restart

`{"error":"not_found","reason":"Database does not exist."}`

CouchDB2.log flooded with this:

> [notice] 2017-11-24T03:10:37.191333Z couchdb@localhost <0.334.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:403) <= mem3_shards:load_shards_from_disk/1(line:378) <= mem3_shards:load_shards_from_disk/2(line:407) <= mem3_shards:for_docid/3(line:91) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2017-11-24T03:10:37.191394Z couchdb@localhost emulator -------- Error in process <0.1701.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,407}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,91}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}

## Possible Solution
None, install via homebrew?

## Steps to Reproduce (for bugs)
1. Update to latest macOS
2. Update to latest CouchDB
3. Check log

## Context
No white space in mounts - https://github.com/apache/couchdb/issues/732, https://github.com/apache/couchdb/issues/840 

> /bin/df -lk
> Filesystem   1024-blocks      Used Available Capacity iused               ifree %iused  Mounted on
> /dev/disk1s1   488347692 311004840 175607980    64% 3356060 9223372036851419747    0%   /
> /dev/disk1s4   488347692   1048596 175607980     1%       1 9223372036854775806    0%   /private/var/vm

There are no DBs created. Created one, still same error

> [notice] 2017-11-24T03:27:07.461656Z couchdb@localhost <0.17549.0> be1954d2d2 127.0.0.1:5984 127.0.0.1 undefined GET /testdb1?_=1511494027049 200 ok 1

Uninstalled homebrew and all packages to avoid conflicts! No change.

## Your Environment
CouchDB 2.1.1
macOS High Sierra 10.13.1

**Comment by mr-bobz** [comment] 2017-11-24 07:47
Found some info here that I need to setup database before using. Don't remember doing this last time, may be too long! Would have been great if this was shown as welcome page in Fauxton console :-)

https://issues.apache.org/jira/browse/COUCHDB-3163
https://stackoverflow.com/questions/41553458/couchdb-2-0-installation-error
https://github.com/apache/couchdb/issues/739

Created the tables using the following:

> curl -X PUT http://127.0.0.1:5984/_users
> curl -X PUT http://127.0.0.1:5984/_replicator
> curl -X PUT http://127.0.0.1:5984/_global_changes

Now log flooded with:

> [info] 2017-11-24T07:43:09.316275Z couchdb@localhost <0.218.0> -------- couch_proc_manager <0.1739.4> died normal
> [error] 2017-11-24T07:43:09.316293Z couchdb@localhost <0.5611.1> 8acc89488f OS Process Error <0.1739.4> :: {os_process_error,{exit_status,134}}

**Comment by snollygolly** [comment] 2017-11-27 04:17
I have the same problem as well.  Any idea what's causing those errors?  I'm unable to create views from inside of Fauxton or within my app.

**Comment by mr-bobz** [comment] 2017-11-27 15:14
Yes, creating index/view seems to be where it is failing for me too now:

> [{"id":"_design/resources","error":"unknown_error","reason":"undefined"},{"id":"_design/annotations","error":"unknown_error","reason":"undefined"}]

**Comment by lyudmil** [comment] 2017-11-28 22:34
@snollygolly, @mr-bobz, I think you might want to take a look at #979. The current workaround seems to be `brew install nspr`, but the real fix is to package the missing libraries into the app.

**Comment by snollygolly** [comment] 2017-11-28 23:29
Thanks @lyudmil!

I installed that package like you suggested and I was able to create a view with no problems.

**Comment by brendand** [comment] 2017-12-02 22:32
I don't have a brew command on my Mac, so I can't install nspr. 

Is there a way to get this into the package itself so it's not a third-party dependency?

**Comment by mr-bobz** [comment] 2017-12-04 01:35
Ideally CouchDB package for macOS should handle it.

For now, you can install brew from here 
https://brew.sh/
eg: 

> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


and run 

> brew install nspr

**Comment by brendand** [comment] 2017-12-05 23:12
Yup. I did that and it does work. I was just hoping to not have to have home-brew on my Mac. Just more stuff to keep track of. Plus teaching my customers how to install home brew isn't the most pleasant thing to have to do. Kind of takes the whole "it just works" thing on the Mac to a bad place.

**Comment by craftzdog** [comment] 2017-12-06 05:52
I've got below error log flooded:

```
[error] 2017-12-06T05:48:15.347175Z couchdb@localhost <0.1994.0> -------- OS Process Error <0.6574.1> :: {os_process_error,{exit_status,134}}
```

After having `brew install nspr`, it got fixed! Thanks @lyudmil.

**Comment by sauoq** [comment] 2017-12-15 12:13
Installing homebrew is not a satisfactory solution as brew and macports don't always play well together. I use macports. Manually linking or copying the library to the brew install location is less than ideal.

**Comment by johs** [comment] 2018-01-02 14:27
Installing homebrew or macports requires installing/updating Xcode, so by the time a new user has figured out that this is the workaround to make CouchDB work on a Mac, I am afraid we have host her/him forever.

**Comment by wohali** [comment] 2018-01-16 19:42
Duplicate of #979.

**Closed by wohali** 2018-01-16 19:42 UTC
Labels: macos
