### ISSUE TITLE
Admin username with = in name gets corrupted on initial password encrypt

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2188] opened 2019-09-15 06:15 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

>`COUCHDB_USER=YWRtaW4=` shall give
>
> ```
> [admins]
> YWRtaW4= = -pbkdf2-3202582cea5a342e5a7f94d12475f55e0ff53545,ac28cb29b8c4fe48d16bf5e2a76cdc8a,10
> ```
>
> instead gives:
> ```
> [admins]
> YWRtaW4 = -pbkdf2-3202582cea5a342e5a7f94d12475f55e0ff53545,ac28cb29b8c4fe48d16bf5e2a76cdc8a,10
> ```

## Steps to Reproduce

Add an admin user to `local.ini` with an equals sign in the username and an unencrypted password, then start CouchDB. CouchDB will encrypt the password and remove the equals sign from the admin user's name.

## Expected Behaviour

Equals sign in admin user name should not be removed.

## Your Environment

* CouchDB Version used: `master`
* Browser name and version: n/a
* Operating System and version: n/a

## Additional context

Initially reported in apache/couchdb-docker#134:

**Comment by iilyak** [comment] 2019-09-16 09:32
> Equals sign in admin user name should not be removed.

I am not sure it is a good idea to allow equal signs (and other things which have special meaning in URL) in the context of username. Is it documented anywhere that we really support it?

**Comment by wohali** [comment] 2019-09-16 14:20
It's not documented anywhere that it's not supported, either. ;)

I'm positive people have equals signs in their passwords.

**Comment by iilyak** [comment] 2019-09-17 14:12
Password should be ok. But I personally never saw a project which supports special characters in the user name.

**Comment by Kenzku** [comment] 2019-12-02 11:00
@iilyak 

> I am not sure it is a good idea to allow equal signs

I have some enterprise customers coming back and asking why `=` sign or some special characters are not allow in the encoded/unencoded values

**Comment by florianb** [comment] 2020-02-13 11:32
I'm pretty new to Erlang but this is what i found out on my search for implemented escape-mechanisms.

I think this issue is caused by a malicious call or implementation of `config_utils:implode` (see [config_util.erl:48](https://github.com/apache/couchdb-config/blob/8e0dbf5d6bb27c831b3bd27a020be07cab0e96d0/src/config_util.erl#L48)):

```erlang
implode(List, Sep) ->
    implode(List, Sep, []).

implode([], _Sep, Acc) ->
    lists:flatten(lists:reverse(Acc)); % 
implode([H], Sep, Acc) ->
    implode([], Sep, [H|Acc]);
implode([H|T], Sep, Acc) ->
    implode(T, Sep, [Sep,H|Acc]).
```

It seems like that formerly removed equal signs (see [config.erl:396](https://github.com/apache/couchdb-config/blob/8e0dbf5d6bb27c831b3bd27a020be07cab0e96d0/src/config.erl#L396)):

```erlang
case re:split(Line2, "\s?=\s?", [{return, list}]) of
% ...
[ValueName|LineValues] -> % yeehaw, got a line!
    RemainingLine = config_util:implode(LineValues, "="),
```

(which are passed to the `Sep` argument) are not reinserted. At this place a `string.join` might be the better alternative.

However, the ini parser itself doesn't seem to handle edge cases safely.
From my work at editorconfig (and our efforts there to create a strict ini grammar) i can say the current implementation also forbids semicolons in values which might be the next problem to deal with.
And it looks like the parser could be simplified to gain robustness.

**Comment by nickva** [comment] 2023-11-13 07:27
This is now fixed

**Closed by nickva** 2023-11-13 07:27 UTC
Labels: bug

**Comment by Kenzku** [comment] 2023-11-13 15:01
thank you a million
