### ISSUE TITLE
Sporadic `unknown_error : normal` errors

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb#1600] opened 2018-09-10 19:58 UTC
Occasionally, when using Cookie auth, the /_all_docs endpoint returns 401, and logs an unusual error. I have observed this on both the /_users and /_replicator databases. Unknown if it happens on non-system databases.

## Expected Behavior
I would expect a normal response

## Current Behavior

Two log samples (both from CouchDB 2.2.0 running in Docker):

[notice] 2018-09-10T19:41:21.627729Z nonode@nohost <0.718.0> 631255b1ec localhost:6004 172.17.0.1 undefined GET /_users/_all_docs?include_docs=true 401 ok 1
[error] 2018-09-10T19:41:21.639919Z nonode@nohost <0.719.0> ec87d65d26 req_err(2525593956) unknown_error : normal
    [<<"chttpd:catch_error/3 L353">>,<<"chttpd:handle_req_after_auth/2 L319">>,<<"chttpd:process_request/1 L300">>,<<"chttpd:handle_request_int/1 L240">>,<<"mochiweb_http:headers/6 L124">>,<<"proc_lib:init_p_do_apply/3 L247">>]

[notice] 2018-09-10T19:46:18.065472Z nonode@nohost <0.719.0> 1e9079ba74 localhost:6004 172.17.0.1 undefined GET /_replicator/_all_docs?include_docs=true 401 ok 3
[error] 2018-09-10T19:46:18.069496Z nonode@nohost <0.720.0> f23a984706 req_err(2525593956) unknown_error : normal
    [<<"chttpd:catch_error/3 L353">>,<<"chttpd:handle_req_after_auth/2 L319">>,<<"chttpd:process_request/1 L300">>,<<"chttpd:handle_request_int/1 L240">>,<<"mochiweb_http:headers/6 L124">>,<<"proc_lib:init_p_do_apply/3 L247">>]

## Steps to Reproduce (for bugs)
As stated above, this is a sporadic error.  It doesn't always happen, but the requests that generated the above errors:

GET /_users/_all_docs?include_docs=true HTTP/1.1
Host: localhost:6004
Accept: application/json
Content-Type: application/json
Cookie: AuthSession=YWRtaW46NUI5NkM4RTE6pxr5rMbRBHJgbCdnRzQO0JBuzcI
User-Agent: Kivik CouchDB driver/2.0.0-prerelease (Language=go1.8.7; Platform=amd64/linux)

GET /_replicator/_all_docs?include_docs=true HTTP/1.1
Host: localhost:6004
Accept: application/json
Content-Type: application/json
Cookie: AuthSession=YWRtaW46NUI5NkNBMEE6UJcyxbwz2W6vinTcScdUNX5iQcw
User-Agent: Kivik CouchDB driver/2.0.0-prerelease (Language=go1.9.7; Platform=amd64/linux)

## Your Environment
I have observed this on CouchDB 1.7.1, 2.0.0, 2.1.2, and 2.2.0, but only in Travis-CI on my Kivik project. I have been unable thus far to reproduce this locally on any version.

I will continue to try to find a reliable reproduction case.

**Comment by nickva** [comment] 2018-09-16 07:16
Interesting find, @flimzy 

I have seen this error before as well. But don't have a good explanation for it yet. I wonder how it correlates with Erlang versions. For example, have you seen it on some Erlang versions (20.0) happen more than on others

**Comment by flimzy** [comment] 2018-09-16 11:04
I've been testing against the official Docker images for CouchDB 1.7.1 through 2.2.0, which corresponds with Erlang OTP/17 through Erlang OTP/19, respectively.  I have seen the error on every version, and have not noticed a higher occurrence on any specific version, but I also likely would not have noticed if one version happened more than the other, since a single failure will cause my test suite to report a failure.

**Comment by wohali** [comment] 2018-11-14 00:13
I'd like to fix this in 2.3.0, but without more info from @nickva on a possible reason, I'm going to move it out of this milestone.

**Comment by jaydoane** [comment] 2018-11-20 00:51
I tried to repro using this very simple test:
```elixir
  test "https://github.com/apache/couchdb/issues/1600", _ctx do
    sess = Couch.login("adm", "pass")
    target_db = "_users" # also tried _replicator here
    for _i <- 0..10000 do
      resp = Couch.Session.get(sess, "/#{target_db}/_all_docs?include_docs=true")
      assert resp.status_code == 200
    end
  end
```
but it ran to completion on several attempts.

@nickva do you recall whether you saw that error from a containerized or bare metal couch?

@flimzy how many documents were in your _users and _replicator dbs when you saw that issue? Since you were using the official docker images, were those just single node "clusters"?

**Comment by wohali** [comment] 2018-11-22 17:50
@flimzy without a solid reproducible test case, I'm afraid I have to remove this from the 2.3.0 milestone.

We'd love to get back to this once there's a reliable, reproducible test case.

**Comment by natevw** [comment] 2019-01-26 00:18
I think at least in my case these errors are simply a result of the client dropping its connection to CouchDB. I added some code to my middleware in support of a little experiment:

* Each time my middleware starts, it randomly decides whether to fetch continuous changes.
* I made sure to avoid any other requests to my middleware and therefore to CouchDB

Here's a sample log:

```
4:04:33 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:04:34 PM dev_web.1 |  not monitoring changes
4:04:34 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db

4:04:54 PM dev_web.1 |  Program node middleware.js exited with code null
4:04:54 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:04:54 PM dev_web.1 |  not monitoring changes
4:04:54 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db

4:05:14 PM dev_web.1 |  Program node middleware.js exited with code null
4:05:14 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:05:15 PM dev_web.1 |  MONITORING CHANGES
4:05:15 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db

4:05:38 PM dev_web.1 |  Program node middleware.js exited with code null
4:05:38 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:05:38 PM dev_web.1 |  MONITORING CHANGES
4:05:38 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db

4:05:44 PM dev_db.1  |  [error] 2019-01-26T00:05:44.996419Z dev_env-couchdb@localhost <0.13577.22> 04cdfa9352 req_err(1125717067) unknown_error : normal
4:05:44 PM dev_db.1  |      [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_req
4:05:44 PM dev_db.1  |  >  uest_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]

4:08:09 PM dev_web.1 |  Program node middleware.js exited with code null
4:08:09 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:08:09 PM dev_web.1 |  not monitoring changes
4:08:10 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db

4:08:17 PM dev_db.1  |  [error] 2019-01-26T00:08:17.562625Z dev_env-couchdb@localhost <0.13974.22> 0908a8896c req_err(1125717067) unknown_error : normal
4:08:17 PM dev_db.1  |      [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_req
4:08:17 PM dev_db.1  |  >  uest_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]

4:16:32 PM dev_web.1 |  Program node middleware.js exited with code null
4:16:32 PM dev_web.1 |  Starting child process with 'node middleware.js'
4:16:32 PM dev_web.1 |  MONITORING CHANGES
4:16:32 PM dev_web.1 |  Listening on 4000, using backend http://localhost:4100/my-db
```

Each time you see "Program node middleware.js exited with code null" was me killing the middleware process. I think the pattern's pretty clear.

1. First restart shown (4:04:33) is ambiguous since the log doesn't include whether the *previous* run was monitoring or not, but note that that middleware instance — call it "Process-1" — does **not** monitor changes.
2. There is no error after Process-1 is killed (at 4:04:54) and Process-2 is started (again **not** monitoring changes).
3. There is no error after Process-2 is killed (at 4:05:15) and Process-3 is started. Note that Process-3 **does** monitor changes.
4. After Process-3 is killed (at 4:05:38), there *is* an error shortly after (at 4:05:44). The new Process-4 **does** monitor changes.
5. After Process-4 is killed (at 4:08:09) there is again an error shortly after (at 4:08:17). The new Process-5 does *not* monitor changes.
6. After Process-5 is killed (at 4:16:32) there was no error.

**Comment by natevw** [comment] 2019-01-26 00:34
Hah, forget all that "Process-N" mumbo-jumbo. Here's an easy repro:

1. In one terminal: `curl "http://admin:password@localhost:5986/some-db/_changes?since=now&feed=continuous"`
2. From another terminal, kill that curl process.

Doesn't seem to happen as quickly or reliably if simply Ctrl-C'ing curl, or when `feed=longpoll` but maybe the delay between the connection dropping and the error logging is just longer than I am patient in these cases. (After a few minutes I seem to get a pile of errors in my CouchDB log but by then I've forgotten what I was testing…)

**Comment by wohali** [comment] 2019-02-07 21:19
Another repro on this: saw it when enabling maintenance mode on a node.

**Comment by vincnetas** [comment] 2019-02-14 09:47
Also getting this error on 2.3.0 after upgrade

```
[error] 2019-02-14T09:43:19.449719Z couchdb@127.0.0.1 <0.21732.2> 98da3606d3 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:23.700648Z couchdb@127.0.0.1 <0.1825.2> d9b3af3f17 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:24.430878Z couchdb@127.0.0.1 <0.16651.1> 707829a6c5 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:26.462755Z couchdb@127.0.0.1 <0.17367.1> 388d47a1f1 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:26.551631Z couchdb@127.0.0.1 <0.4304.2> 7d1044c05c req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:27.180748Z couchdb@127.0.0.1 <0.17700.1> e34e436ed1 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2019-02-14T09:43:27.262753Z couchdb@127.0.0.1 <0.4690.2> 8c27bdd1dd req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
```

Using single node setup, with >300K DB's. Disabled cookie authentication, but still getting these errors.

```
allow_persistent_cookies = false
authentication_handlers = {couch_httpd_auth, default_authentication_handler}
```

**Comment by sergey-safarov** [comment] 2019-03-05 20:48
Looks as this related to disk speed and request rate.
After disk data is cached into disk memory, issue `"chttpd:handle_req_after_auth/2 L322"`  goes away.

Will make same test on SSD disk

**Comment by sergey-safarov** [comment] 2019-03-05 23:38
On SSD disk i not have more error like
```
chttpd:handle_req_after_auth/2 L322
```
Looks as issue related to disk performance.

**Comment by vincnetas** [comment] 2019-03-06 06:44
We have this issue on SSD's (as mentioned in comment 20 days ago)

**Comment by cmaas** [comment] 2019-03-11 09:55
Same issue here, also an SSD on a VPS. Version 2.2.0. Started yesterday morning, never had this error message before.

@sergey-safarov How did you measure disk speed and request rate exactly?

**Comment by m1cka** [comment] 2019-05-23 07:46
Same problem:
Ubuntu 18.04.2 LTS (on SSD)
Docker-ce 18.09.6
image: "apache/couchdb:2.3.1"

**Comment by iilyak** [comment] 2019-06-19 01:34
> @wohali Another repro on this: saw it when enabling maintenance mode on a node.

# Theory : Some update events are not delivered when node is in MM.

The `chttpd_auth_cache` server listens for changes to users database. So it can [evict](https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd_auth_cache.erl#L165) updated entries from the cache. The changes listener is implemented using `fabric:changes/4`. The `fabric:changes` [iterates](https://github.com/apache/couchdb/blob/master/src/fabric/src/fabric_db_update_listener.erl#L70:L73) over all shards for users database and calls [`start_update_notifier/1`](https://github.com/apache/couchdb/blob/master/src/fabric/src/fabric_db_update_listener.erl#L76) for every shard. The [`start_update_notifier/1`](https://github.com/apache/couchdb/blob/master/src/fabric/src/fabric_db_update_listener.erl#L76:L81) is implemented as follows:
```
start_update_notifier(DbNames) ->
    {Caller, Ref} = get(rexi_from),
    Notify = config:get("couchdb", "maintenance_mode", "false") /= "true",
    State = #cb_state{client_pid = Caller, client_ref = Ref, notify = Notify},
    Options = [{parent, Caller}, {dbnames, DbNames}],
    couch_event:listen(?MODULE, handle_db_event, State, Options).
```

The notification about a database update is not send if node is in the maintenance mode. The failure mode is as follows:

- put node in the MM
- cause changes listener restart (it would be restarted automatically after config:get("httpd", "changes_timeout", "60000")) milliseconds.
- update user 
- we would miss db_update event (because Notify would be false)
- the ets_lru cache backing chttpd_auth_cache would still be holding old entry.

**Comment by iilyak** [comment] 2019-06-19 11:37
> @iilyak Theory : Some update events are not delivered when node is in MM.

However it wouldn't explain why errors are happening only with system databases.

**Comment by arifcse019** [comment] 2019-08-22 16:37
Same issue, CouchDB 2.3.1, SSD disk

**Comment by natevw** [comment] 2019-09-04 16:49
Yes, to me I continue seeing similar error logs (and with non-system databases) and I still suspect it's due to dropped client connections.

**Comment by alexpirine** [comment] 2019-09-19 09:30
We also see these errors…

**Comment by pchrzasz** [comment] 2019-10-16 09:57
Same issue on 2.3.0. Also we see that connections to couchdb are timeouted (5s timeout).

**Comment by Geko1990** [comment] 2019-10-22 13:50
We get the same errors since we use proxy authentification... all request work... but if we use some with feed=continuous we get that error. I think the problem is that the proxy is not keeping the connection alive and its the same as killing a curl request. Still needs a lot of testing but it keeps coming.

**Comment by enst** [comment] 2019-11-01 15:40
Seeing the same issue on our 3-node 2.3.1 cluster.
A bunch of logs like the following:
Nov 01 15:00:56 na5 d89aee6fe164[937]: [error] 2019-11-01T15:00:56.954747Z couchdb@couchdb3.internal <0.19841.787> 3707979fa5 req_err(1125717067) unknown_error : normal
Nov 01 15:00:56 na5 d89aee6fe164[937]:     [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]

Oct 30 16:37:58 na5 d89aee6fe164[937]: [error] 2019-10-30T16:37:58.197437Z couchdb@couchdb3.internal <0.19845.207> f1628abb46 req_err(1125717067) unknown_error : normal                                                                                                                 
Oct 30 16:37:58 na5 d89aee6fe164[937]:     [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]

**Comment by olivenvrac** [comment] 2019-11-28 16:12
hello
I'v got the same issue on a CouchDB single node with 3 VCPU Intel(R) Xeon(R) CPU E7- 4830  @ 2.13GHz and 4 Go ram
couchdb "2.3.0"
Red Hat Enterprise Linux Server release 7.2 (Maipo)

We have an mobile application with 150 users wich use CouchDB and embed a PouchDB database with http synchronisation in longpulling mode with the couchdb instance
There is approximatively 100 simultanous synchronisation with the cookies authentification. 
data reside on a disk cached by a sanshare connection with a lot of cache memory 

errors :
[<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]

**Comment by skeyby** [comment] 2020-06-25 08:17
I'd like to join the Party....

I think this is the same problem:

```
[error] 2020-06-25T07:59:19.755854Z couchdb@10.133.136.126 <0.29723.204> 77cd8945da req_err(3717872069) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L249">>]
[error] 2020-06-25T08:01:36.801577Z couchdb@10.133.136.126 <0.11743.199> 5a40992a00 req_err(3717872069) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L249">>]
[error] 2020-06-25T08:01:42.651561Z couchdb@10.133.136.126 <0.27527.200> e1b4f6821b req_err(3717872069) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L249">>]
```

FreeBSD 12.1, CouchDB 2.3.1, Erlang 21.3.8.14.

A lot of PouchDB clients replicating from a Single Database.

**Comment by janl** [comment] 2020-06-25 08:30
@skeyby just checking, does this cause any noticeable issues for your application (✌️) or is this more inconvenient log noise (which we should still investigate of course, just trying to get a sense of urgency here)

**Comment by wohali** [comment] 2020-06-25 17:54
FYI reviewing the history of this, I don't see anyone reporting this issue against CouchDB 3.x.

**Comment by skeyby** [comment] 2020-06-26 12:34
@janl no noticeable problems from the application side, it's just generating like 10MBs of log per day...

**Comment by ahmedsajid** [comment] 2020-06-29 02:23
I have recently started noticing these normal errors too. This seems to be causing problem on application side where the application has to retry the query.

CouchDB 2.3.1
doc_count 1146523

```
[error] 2020-06-29T01:47:40.135242Z nonode@nohost <0.16344.1747> d9b86d05d1 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:52:16.800967Z nonode@nohost <0.7070.1747> 6e3f86e7d2 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:52:37.457872Z nonode@nohost <0.22879.1746> dd23899df1 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:53:38.011332Z nonode@nohost <0.13826.1747> f017584ecd req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:54:21.724277Z nonode@nohost <0.10653.1738> a29cd9aab0 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:54:23.644179Z nonode@nohost <0.25576.1746> 38ad2a22d1 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:54:44.433040Z nonode@nohost <0.14191.1747> 1d48919e2f req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:54:50.377741Z nonode@nohost <0.29280.1747> c5d56778d0 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-06-29T01:55:01.151052Z nonode@nohost <0.22135.1747> 1f97463eea req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
```

**Comment by pavellzubkov** [comment] 2020-07-14 19:35
now i get same error with ibmcom/couchdb3:3.1.0 image on windows desktop docker (v 2.3.0.3). 
i have Ryzen7 3700u proc, 16gb Ram , SSD
last errors:
```
[error] 2020-07-14T19:16:09.909029Z couchdb@127.0.0.1 <0.18562.88> 23794d840a req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-07-14T19:16:09.915970Z couchdb@127.0.0.1 <0.19757.88> cd5af352db req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-07-14T19:17:08.686461Z couchdb@127.0.0.1 <0.31109.97> 0eceb5635e req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2020-07-14T19:17:08.703069Z couchdb@127.0.0.1 <0.31500.97> 924c75301e req_err(50502807) unknown_error : normal
    [<<"chttpd:catch_error/3 L358">>,<<"chttpd:handle_req_after_auth/2 L324">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>,<<"proc_lib:init_p_do_apply/3 L247">>]
```
couchdb server fall down and not responding. docker container didn't restart

**Comment by wohali** [comment] 2020-07-14 23:44
Sounds like a browser problem - nothing we can do here.

**Comment by wohali** [comment] 2020-07-14 23:44
Whoops, sorry, didn't mean to close this.

**Comment by pavellzubkov** [comment] 2020-07-15 06:10
Now i stop pouchdb replications before user logout and all ok. No errors in couch log, all works fine. Obviously couchdb generate errors  and hold connection opened when user with opened live replications sent DELETE request to _session.

**Comment by wohali** [comment] 2020-07-15 15:33
> I think at least in my case these errors are simply a result of the client dropping its connection to CouchDB.

This is the current best likely reason for this issue, unless anyone else has reasons this may be occurring.

@iilyak 's theory is not applicable because we see this without any node in MM.

Suppressing these logging comments is probably the only thing that needs to happen here, anyone want to have a go at a PR?

**Comment by style95** [comment] 2021-12-09 08:27
I am facing the same issue, is there any update on this issue?

**Comment by nickva** [comment] 2021-12-10 19:32
@style95 what version of CouchDB are you running?

3.1.2 and 3.2.1 should have this fix for this already https://github.com/apache/couchdb/pull/3102

NOTE: There are 3.2.1 packages available in the usual repos, and the source available at https://dlcdn.apache.org/couchdb/source/3.2.1/apache-couchdb-3.2.1.tar.gz . We just haven't updated the website as we're waiting on the Windows packaging.

**Closed by nickva** 2021-12-10 19:32 UTC

**Comment by style95** [comment] 2021-12-13 00:52
@nickva Thank you for sharing.
I am using CouchDB v2.3.1, considering upgrading it to 3.2.1.
