### ISSUE TITLE
Add support for Ubuntu 24.04 LTS ("noble")

### ISSUE THREAD

**Issue by DarrenCook** [apache/couchdb#5359] opened 2024-12-12 08:46 UTC
## Summary

CouchDB can't be installed on Ubuntu 24.04 LTS as there is no deb.

It has been the recommended long-term-support version for people to install since April, so is an obvious choice for servers.

## Desired Behaviour

We want to be able to follow the documentation at:
  https://docs.couchdb.org/en/latest/install/unix.html#enabling-the-apache-couchdb-package-repository

But it fails because "noble" is returned for `${VERSION_CODENAME}`

## Possible Solution

Add "Ubuntu 24.04 LTS" to the list at https://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

And add the corresponding deb release, or course :-)

**Comment by big-r81** [comment] 2024-12-14 15:27
Closing this as duplicate of #5077.

**Closed by big-r81** 2024-12-14 15:27 UTC
Labels: enhancement, needs-triage
