### ISSUE TITLE
CloudDB just stops working D:

### ISSUE THREAD

**Issue by jamessc0tt** [apache/couchdb#557] opened 2017-05-31 20:52 UTC
Currently running CloudDB for my GTA FiveM server, after installation it works for a while but then just stops. I've tried re-running it from the batch file in /bin but it just errors and closes.

Log file: https://pastebin.com/3CnWY8Wf

## Your Environment

* Version used: Version 2.0.0.1
* Browser Name and version: Chrome (Latest)
* Operating System and version (desktop or mobile): Windows Server 2012 (RDP)

**Comment by wohali** [comment] 2017-05-31 20:55
There are no errors in this logfile paste to go on. It shows a few restarts but that's it.

If you open a command prompt yourself and run the batch file in bin (couchdb.cmd) and run it, is an error displayed?

Are you sure your server is not running out of RAM or CPU and the OS isn't killing CouchDB for some reason?

**Comment by jamessc0tt** [comment] 2017-05-31 21:00
http://wanconnectors.co.uk/i/t1exr.png < the error when I run it through cmd..

Don't think the issue is with RAM or CPU, sitting at 13% CPU and 25% Memory usage.

**Comment by nickva** [comment] 2017-05-31 21:06
I think you might have started multiple couchdb nodes on the same machine. Going by the "name couchdb@localhost seems to be in use by another Erlang node" error message.

**Comment by jamessc0tt** [comment] 2017-05-31 21:08
I mean, I've uninstalled and re-installed it a few times because that's the only way it gets working, but none of them are running (or none look like they're running).

Is there a way I'd be able to modify that or close some?

**Comment by wohali** [comment] 2017-05-31 21:14
Go to the Services control panel (under Administrative Tools) and use the option there to restart the service rather than using the batch file.

**Comment by jamessc0tt** [comment] 2017-05-31 21:18
I have just tried that, it doesn't seem to make a difference, so I stopped it and tried to run the batch file and got this error instead: http://wanconnectors.co.uk/i/l8h7j.png

**Comment by wohali** [comment] 2017-05-31 21:19
The user you're using to run the service from the command line doesn't have write access. You'll need to open an Administrator prompt from which to run CouchDB.

**Comment by jamessc0tt** [comment] 2017-05-31 21:22
Sorry about that, didn't even think. It sits on `kernel-poll is not supported; "K" parameter ignored` and does nothing.. http://wanconnectors.co.uk/i/t4ucv.png

**Comment by wohali** [comment] 2017-05-31 21:24
That's a good sign. That means CouchDB is running.

**Comment by wohali** [comment] 2017-05-31 21:24
I don't see any evidence of what's causing CouchDB to exit in the logs. Closing this issue.

**Comment by jamessc0tt** [comment] 2017-05-31 21:25
I mean, it's not solved? What am I supposed to do?

**Closed by wohali** 2017-05-31 21:24 UTC

**Comment by wohali** [comment] 2017-05-31 21:45
This is probably a duplicate of https://github.com/apache/couchdb/issues/508 .

Your log files have nothing for us to go on that suggest there's anything else going on here. What more do you expect us to do?
