### ISSUE TITLE
chttpd purge test failure

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2424] opened 2020-01-08 05:15 UTC
Seen this twice now:

```
::in function chttpd_purge_tests:'-create_db/1-fun-0-'/1 (test/eunit/chttpd_purge_tests.erl, line 43)
in call from chttpd_purge_tests:setup/0 (test/eunit/chttpd_purge_tests.erl, line 32)
**error:{assert,[{module,chttpd_purge_tests},
{line,43},
{expression,"Status =:= 201 orelse Status =:= 202"},
{expected,true},
{value,false}]}
```

**Comment by nickva** [comment] 2020-01-08 23:17
I noticed this as well. Dug into the logs and see that it was a flaky auth failure:


```
[notice] 2020-01-08T22:49:17.394510Z nonode@nohost <0.7059.0> -------- config: [admins] chttpd_db_test_admin deleted for reason nil
[notice] 2020-01-08T22:49:17.395010Z nonode@nohost <0.7059.0> -------- config: [admins] chttpd_db_test_admin set to pass for reason nil
[notice] 2020-01-08T22:49:17.396323Z nonode@nohost <0.7059.0> -------- config: [admins] chttpd_db_test_admin set to -pbkdf2-81cf7a744b3b0715c06d32436a3c0adee57502fb,01459c94b2344081794c3d0ff8a4ccb4,10 for reason nil
[notice] 2020-01-08T22:49:17.399415Z nonode@nohost <0.7339.0> b3933e8c08 127.0.0.1:32949 127.0.0.1 undefined PUT /eunit-test-db-779d9be929aecb36d3f07bad0914b21a 401 ok 4
[notice] 2020-01-08T22:49:17.400575Z nonode@nohost <0.7059.0> -------- config: [admins] chttpd_db_test_admin set to pass for reason nil
```
 `PUT /eunit-test-db-779d9be929aecb36d3f07bad0914b21a 401` was expected to be 202 or 201 but is 401 instead

**Comment by jiangphcn** [comment] 2020-01-09 00:28
thanks @nickva for getting further on this issue. I can't reproduce locally. knowing that this is flaky and happened on CI. Where did you find couchdb log?

**Comment by nickva** [comment] 2020-01-09 04:54
np @jiangphcn!

@wohali had added a nifty way for the log files to be uploaded to a server on test failure.  If you look at the end in the Jenkins logs, you'll see a URL where it was uploaded. The only thing is that `jenkins` gets replaced with `****`. So you'd just replace jenkins back in and then download the logs with`wget` or `curl`.

**Comment by davisp** [comment] 2020-01-09 15:37
Found it. All of the other places we do this we set the config value to the already hashed value. chttpd_purge_tests does not which means we're racing the auto-hasher. Fix is incoing.

**Closed** 2020-01-09 16:03 UTC
Labels: bug, testsuite
