### ISSUE TITLE
NSSM.EXE is displayed as a threat.  alert notification issued by McAfee antivirus program.

### ISSUE THREAD

**Issue by arulrajmichael** [apache/couchdb#2161] opened 2019-09-02 13:31 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
CouchDb Services are not starting up and Ports are not listening

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by arulrajmichael** [comment] 2019-09-02 13:33
Version Used Couch Db 2.3.1
Windows 7 Operating System.
10.6 Version Of McAfee Endpoint Security

**Comment by wohali** [comment] 2019-09-02 17:21
Duplicate of #1302 and #795.

#1303 is the ticket to track its replacement.

**Closed by wohali** 2019-09-02 17:21 UTC
Labels: bug, needs-triage
