### ISSUE TITLE
Apache CouchDB Windows Service Paused

### ISSUE THREAD

**Issue by driglou** [apache/couchdb#508] opened 2017-05-07 19:34 UTC
I downloaded CouchDB as I was preparing my PouchDB project. My OS is Windows 10.
However when I tried to open Fauxton it said Connection refused, I went to look in my Services and I saw that Apache CouchDB Service is paused. I Stop ir and Start it, however I am getting this.
![1](https://cloud.githubusercontent.com/assets/5339578/25784410/fab61026-3374-11e7-91c6-3abb9304ba19.png)

I tried googling all possible solutions, however I did not find what is exactly wrong. As there is no exact error and I do not understand CouchDB exactly the way it works or on what it relies, I can't seem to find solution.

Please let me know if I can provide any more details that would help to identify the issue.

**Comment by wohali** [comment] 2017-05-07 20:38
Hi there,

This is a known issue we will address with the next release of CouchDB. For now, you will need to update the permissions of your C:\CouchDB directory (and all children directories) to allow write access to whatever user is running your service.

**Comment by driglou** [comment] 2017-05-08 11:39
Thank you for quick response.

I did what you said, however the problem still remains.
I added full access the the C:\CouchDB and its childrens, I restarted PC and but the issue still remains as it was.
Either I need to do something more or I did not do exactly what you suggested me to do.

![2](https://cloud.githubusercontent.com/assets/5339578/25802687/183b8676-33fc-11e7-8941-ec4e9f165cc5.png)

**Comment by wohali** [comment] 2017-05-08 18:32
Try adding the "LOCAL SERVICE" account and give it full control. Users shouldn't have it.

**Comment by driglou** [comment] 2017-05-08 19:44
The problem still remains exactly as it was.

Is there anything more I can do?

Also before when I installed CouchDB for the first time few month ago, everything was working perfectly out of the box, it was still v2 at that time I think. How can I make sure to have clean install of it?

**Comment by smeedledee** [comment] 2017-05-12 23:56
I'm also still having this problem after trying the solution above. My install is completely fresh though.

**Comment by FodOskar** [comment] 2017-05-13 15:08
Guys try to start couchdb with the couchDB.batch file in install/couchDB/bin... Start with sysadmin permission. On win 10 system block couchdb with normal start.

**Comment by toyish** [comment] 2017-05-20 20:51
Same problem here, tried everything but couchdb's windows service refuse to start. Any clue when this release that fix this issue is suppose to be released?

**Comment by wohali** [comment] 2017-05-20 20:54
The workaround for now is to use what @FodOskar says and run the `couchdb.cmd` file as administrator manually. We'll get a fix out for this with the upcoming 2.1 release, which should happen in the next couple of weeks.

**Comment by nueko** [comment] 2017-06-10 20:41
it is NSSM related issue, see [here](https://nssm.cc/download)
> Windows 10 Creators Update

>2017-04-26: Users of Windows 10 Creators Update should use prelease build 2.2.4-101 to avoid an issue with services failing to start. If for some reason you cannot use that build you can also set AppNoConsole=1 in the registry, noting that applications which expect a console window may behave unexpectedly.

>Thanks to Sebasian Krause for the initial diagnosis.

**Comment by wohali** [comment] 2017-06-10 22:09
Thanks for the diagnosis @nueko ! We'll update the version of `nssm.exe` we use in the next build.

**Comment by nueko** [comment] 2017-06-10 22:22
also by copying the pre-release version does work here.

**Comment by DCMay** [comment] 2017-06-14 09:20
run the couchdb.cmd file as administrator manually. does not work for me.

**Comment by wohali** [comment] 2017-06-14 15:54
@dcmay Did you try copying the pre-release version `nssm.exe` from [here](https://nssm.cc/download) over your existing `nssm.exe`?

**Comment by nueko** [comment] 2017-06-14 17:06
@wohali I think @DCMay just run the `/CouchDB/bin/couchdb.cmd` directly

**Comment by dracuslayer** [comment] 2017-07-06 02:28
for those that have windows 10 creators edition just follow this after install and couchdb will work for you https://stackoverflow.com/questions/44107334/couchdb-fails-to-start-after-applying-windows-10-creators-update

**Comment by nueko** [comment] 2017-07-07 02:06
🍭 Great

**Comment by wohali** [comment] 2017-07-07 02:28
This is the same fix that was stated earlier in this thread.

Locking down comments on this for now. We know what the problem is. 2.1 will be released shortly with this fix included.

**Comment by wohali** [comment] 2017-07-09 06:37
I have a newly built version of the 2.0.0 installer with the replaced NSSM, Erlang 18.3 and OpenSSL 1.0.2l. I am waiting for access to the code signing service to be restored, at which point I'll publish the installer as v2.0.0.2.

**Comment by wohali** [comment] 2017-07-11 02:37
The code signing service is out of commission for a few weeks, so rather than hold up the release, I'm releasing it unsigned.

Download it here: 

https://apache.bintray.com/couchdb/win/2.0.0.2/couchdb-2.0.0.2.msi

**Closed by wohali** 2017-07-11 02:37 UTC
Labels: bug, windows
