### ISSUE TITLE
DELETE /db/doc/attachment returns 200 OK for non existing attachments

### ISSUE THREAD

**Issue by TomaszKasowicz** [apache/couchdb#452] opened 2017-03-08 19:48 UTC
Hi

While playing with doc attachments I found out that CouchDB returns 200 OK and updates document rev when user tries to delete non-existing attachment

Here's an example output
'''
root@5d984b5559b3:/# curl -X PUT 'http://127.0.0.1:5984/testdb'
{"ok":true}
root@5d984b5559b3:/# curl -X PUT 'http://127.0.0.1:5984/testdb/doc' -d '{}'
{"ok":true,"id":"doc","rev":"1-967a00dff5e02add41819138abb3284d"}
root@5d984b5559b3:/#
root@5d984b5559b3:/# curl -X DELETE 'http://127.0.0.1:5984/testdb/doc/attachment?rev=1-967a00dff5e02add41819138abb3284d'
{"ok":true,"id":"doc","rev":"2-7051cbe5c8faecd085a3fa619e6e6337"}
'''

Is this OK? I'm confused because CouchDB API documentation states that I should receive 404

Thank You
Tomasz

**Comment by wohali** [comment] 2017-03-18 08:04
This is a duplicate of https://issues.apache.org/jira/browse/COUCHDB-1594 which shows that this issue has been around since ~CouchDB 1.2. We should fix it, but this is at least not a regression.

@rnewson you might be amused by this one. 👀

**Closed by wohali** 2017-03-18 08:04 UTC
