### ISSUE TITLE
if will support arm linux?

### ISSUE THREAD

**Issue by ericdai** [apache/couchdb#1339] opened 2018-05-24 14:07 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment] 2018-05-24 15:08
Duplicate of #1103 and #892.

**Closed by wohali** 2018-05-24 15:08 UTC
