### ISSUE TITLE
httpd 500 error response: exit reason bad match affecting production

### ISSUE THREAD

**Issue by rambhavaraju** [apache/couchdb#1459] opened 2018-07-21 19:18 UTC
We are getting error in production whenever adding users to _users db this is on couchdb 1.6.1. It is our production server and we are having issues right now in live.

## Current Behavior
here is the stack trace
 httpd 500 error response:
 {"error":"EXIT","reason":"{{badmatch,[]},\n [{couch_query_servers,new_process,3},\n  {couch_query_servers,lang_proc,3},\n  {couch_query_servers,handle_call,3},\n  {gen_server,handle_msg,5},\n  {proc_lib,init_p_do_apply,3}]}"}
[Sat, 21 Jul 2018 08:27:07 GMT] [error] [<0.19655.4895>] ** Generic server couch_server terminating 
** Last message in was {open,<<"a82d67e7f6aa981d3bd7a3f1ab7a277bfcedad949">>,
                           [{user_ctx,
                                {user_ctx,
                                    <<"a82d67e7f6aa981d3bd7a3f1ab7a277bfcedad949">>,
                                    [],
                                    <<"{couch_httpd_auth, cookie_authentication_handler}">>}}]}
** When Server state == {server,"/couchdb",
                            {re_pattern,0,0,
                                <<69,82,67,80,124,0,0,0,16,0,0,0,1,0,0,0,0,0,
                                  0,0,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                  0,0,0,0,0,0,0,0,0,93,0,72,25,77,0,0,0,0,0,0,
                                  0,0,0,0,0,0,254,255,255,7,0,0,0,0,0,0,0,0,0,
                                  0,0,0,0,0,0,0,77,0,0,0,0,16,171,255,3,0,0,0,
                                  128,254,255,255,7,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                  0,0,0,69,26,84,0,72,0>>},
                            500,500,"Thu, 28 Jun 2018 08:55:14 GMT"}
** Reason for termination == 
** {{badmatch,[]},
    [{couch_server,get_lru,1},
     {couch_server,try_close_lru,1},
     {couch_server,maybe_close_lru_db,1},
     {couch_server,open_db,4},
     {gen_server,handle_msg,5},
     {proc_lib,init_p_do_apply,3}]}

[Sat, 21 Jul 2018 08:27:07 GMT] [error] [<0.19655.4895>] {error_report,<0.31.0>,
                          {<0.19655.4895>,crash_report,
                           [[{initial_call,
                              {couch_server,init,['Argument__1']}},
                             {pid,<0.19655.4895>},
                             {registered_name,couch_server},
                             {error_info,
                              {exit,
                               {{badmatch,[]},
                                [{couch_server,get_lru,1},
                                 {couch_server,try_close_lru,1},
                                 {couch_server,maybe_close_lru_db,1},
                                 {couch_server,open_db,4},
                                 {gen_server,handle_msg,5},
                                 {proc_lib,init_p_do_apply,3}]},
                               [{gen_server,terminate,6},
                                {proc_lib,init_p_do_apply,3}]}},
                             {ancestors,
                              [couch_primary_services,couch_server_sup,
                               <0.32.0>]},
                             {messages,
                              [{'$gen_call',
                                {<0.19663.2316>,#Ref<0.0.1449440.31173>},
                                {open,
                                 <<"a1cb95d0731afda3c89ad7efe8657748c94255454">>,
                                 [{user_ctx,
                                   {user_ctx,
                                    <<"a1cb95d0731afda3c89ad7efe8657748c94255454">>,
                                    [],
                                    <<"{couch_httpd_auth, cookie_authentication_handler}">>}}]}}
Your help would be greatly appreciated
We are unable to add normal users through UI, CURL or through the application. This is hindering our production systems.

**Comment by rambhavaraju** [comment] 2018-07-21 19:19
@wohali  could you please help with one.

**Comment by wohali** [comment] 2018-07-21 22:37
Duplicate of #1458.

**Closed by wohali** 2018-07-21 22:37 UTC

**Comment by rambhavaraju** [comment] 2018-07-22 01:33
Thanks wohali
