### ISSUE TITLE
View creation failed on CentOS 7 - CouchDB 2.1.1

### ISSUE THREAD

**Issue by plcollard** [apache/couchdb#1340] opened 2018-05-24 18:28 UTC
CouchDB failed to create views on fresh and updated server with CentOS 7.

## Expected Behavior
Verification of the setup should work .

## Current Behavior
I've first seen the issue in a CentOS 7 server where the packages where updated.
I reproduced the error in a fresh server.

## Steps to Reproduce (for bugs)
1. Install CentOS 7 and update it.
2. Setup repo as described in http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages
3. Install couchdb package and run the setup.
4. Launch the verification in the web interface and the problem appears at the "Create view" steps. 

## Output of logs :
<pre>
[notice] 2018-05-24T18:05:41.461809Z couchdb@127.0.0.1 <0.1522.0> e3ce237828 10.50.50.130:5984 10.50.50.70 undefined GET /verifytestdb 404 ok 3
[notice] 2018-05-24T18:05:41.464446Z couchdb@127.0.0.1 <0.1521.0> 079947299c 10.50.50.130:5984 10.50.50.70 undefined GET /verifytestdb_replicate 404 ok 5
[notice] 2018-05-24T18:05:41.514311Z couchdb@127.0.0.1 <0.1521.0> f2f1464e89 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb 201 ok 41
[notice] 2018-05-24T18:05:41.537452Z couchdb@127.0.0.1 <0.1522.0> 14d27f1fbf 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb/test_doc_1 201 ok 14
[notice] 2018-05-24T18:05:41.554945Z couchdb@127.0.0.1 <0.1522.0> 3063dde463 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb/test_doc_1 201 ok 9
[notice] 2018-05-24T18:05:41.571887Z couchdb@127.0.0.1 <0.1522.0> 7a159de3e1 10.50.50.130:5984 10.50.50.70 admin DELETE /verifytestdb/test_doc_1?rev=2-d588d3e93ee155c5afffdf0247a2c5ef 200 ok 9
[notice] 2018-05-24T18:05:41.602334Z couchdb@127.0.0.1 <0.1522.0> bf8be929af 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb/test_doc_10 201 ok 21
[notice] 2018-05-24T18:05:41.604973Z couchdb@127.0.0.1 <0.1524.0> 1e62a52beb 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb/test_doc_20 201 ok 21
[notice] 2018-05-24T18:05:41.612475Z couchdb@127.0.0.1 <0.2903.0> f116ca8328 10.50.50.130:5984 10.50.50.70 admin PUT /verifytestdb/test_doc_30 201 ok 29
[info] 2018-05-24T18:05:41.639492Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3043.0> died normal
[error] 2018-05-24T18:05:41.639645Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3043.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.660287Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3046.0> died normal
[error] 2018-05-24T18:05:41.660387Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3046.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.675095Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3049.0> died normal
[error] 2018-05-24T18:05:41.675173Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3049.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.694356Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3052.0> died normal
[error] 2018-05-24T18:05:41.694441Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3052.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.708698Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3055.0> died normal
[error] 2018-05-24T18:05:41.708790Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3055.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.731796Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3058.0> died normal
[error] 2018-05-24T18:05:41.731895Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3058.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.748254Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3077.0> died normal
[error] 2018-05-24T18:05:41.748351Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3077.0> :: {os_process_error,{exit_status,1}}
[info] 2018-05-24T18:05:41.762309Z couchdb@127.0.0.1 <0.212.0> -------- couch_proc_manager <0.3080.0> died normal
[error] 2018-05-24T18:05:41.762387Z couchdb@127.0.0.1 <0.3041.0> -------- OS Process Error <0.3080.0> :: {os_process_error,{exit_status,1}}
...
</pre>

## Environment
* Version used: 2.1.1 (installed from repo)
* Operating System: CentOS 7 server
* Kernel: 3.10.0-862.3.2.el7.x86_64

If you need more informations let me know and if you have a solution I would be happy to test it.

Thanks!

**Comment by wohali** [comment] 2018-05-24 19:11
Duplicate of #1293.

**Closed by wohali** 2018-05-24 19:11 UTC
Labels: duplicate

**Comment by adrian1299** [comment] 2018-06-09 01:36
I have the same problem, I didn't resolve, I need help.
