### ISSUE TITLE
Fresh install on OS X High Sierra 10.13.1 errors when you attempt to verify

### ISSUE THREAD

**Issue by stucker71** [apache/couchdb#1004] opened 2017-11-17 10:26 UTC
Fresh install 2.1.1 on OS X High Sierra 10.13.1 gives errors when you attempt to verify.

Error: Replication Failed, expected 4 docs got 3
Error: undefined

## Expected Behavior
No errors

## Current Behavior
Two errors:
Error: Replication Failed, expected 4 docs got 3
Error: undefined

## Steps to Reproduce (for bugs)
Download and install version 2.1.1 on os x high sierra

## Context
unable to proceed.

## Your Environment

* Version used:  2.1.1
* Browser Name and version: Safari Version 11.0.1 (13604.3.5)
* Operating System and version (desktop or mobile): Desktop OS X High Sierra 10.13.1

**Comment by lyudmil** [comment] 2017-11-17 11:10
I'm pretty sure this is a duplicate of #979.

**Comment by stucker71** [comment] 2017-11-17 12:27
You may be correct. When completing verify the status shows a tick for passed. The only failure indicated by a cross is replication.

**Comment by stucker71** [comment] 2017-11-20 10:17
This is same issue as #979. I completed a homebrew install of nspr and this fixed the issue:

brew install nspr

It's a packaging issue.

**Comment by wohali** [comment] 2018-01-16 19:38
Closing in favour of #979

**Closed by wohali** 2018-01-16 19:38 UTC
Labels: macos
