### ISSUE TITLE
CouchDB 2.1 (compaction-daemon) crashes on specific database or documents

### ISSUE THREAD

**Issue by rvanzon** [apache/couchdb#802] opened 2017-09-11 08:17 UTC
After updating to CouchDB 2.1 from 2.0 CouchDB keeps crashing. Starting without databases worked. I decided to import the old data per database and not use the data-directory of 2.0. This worked and I assumed there was some format inconsistency.

But now I created a new database (named nwst-crm-dev-backup) which contains 283 documents now. All like:

`{
  "_id": "activity_10006",
  "_rev": "1-43fc3d3f930dd313dbb26c197249da4b",
  "type": "activity",
  "body": "Description... ",
  "companyId": "company_203",
  "userId": "user_1",
  "subtype": "meeting"
}`

And CouchDB keeps crashing and restarting. 

It could be that the bug is data-related as I tried to replace the documents with placeholder-strings (so that I could send the database here), but then the crash doesn't seems to happen. I tried to find out which kind of data this could be, without luck.

Deleting the database prevents CouchDB from crashing. Also disabling the compaction_deamon keeps CouchDB running.

I am running MacOS Sierra 10.12.4. The disk has enough free space (221 GB) and TimeMachine is switched off.
Location of databases: /Volumes/SD/DBs/CouchDB2

Maybe it's related to https://github.com/apache/couchdb/issues/732, but because the cause of that bug seems to be related to TimeMachine I decided to file a new issue.

Systemlog: https://friendpaste.com/1v8h7GF5gXqyPt6168oa7J

**Comment by willholley** [comment] 2017-09-11 08:24
looks like another instance of #732 - not Time Machine specific, just whitespace in mount points.

**Comment by rvanzon** [comment] 2017-09-11 08:26
Forget to mention, but there are are no whitespaces.

**Comment by willholley** [comment] 2017-09-11 08:42
@rvanzon regarding #732, it doesn't need to be a mount point that's in the database path - any mount point (listed by `$ diskutil list`) containing whitespace could cause the crash, I think, because the compaction daemon [iterates through the system mount points](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_compaction_daemon.erl#L507).

**Comment by acnebs** [comment] 2017-09-23 13:06
I think I'm having the same issue, although I'm running macOS 10.12.6.

[Here are my logs](https://pastebin.com/EGte82sm).

I'd troubleshoot more, but I have no idea where my DBs are located or how I startup on macOS without the DBs.

**Comment by rvanzon** [comment] 2017-09-27 13:41
I could "fix" this by removing the "compaction daemon" (removing it from the config using Fauxton). But now it seems CouchDB adds the config-line once a while and starts crashing CouchDB again.

**Comment by wohali** [comment] 2017-09-27 17:08
If you want to disable the compaction daemon, you should be able to set the following in your `local.ini` or `local.d/*` file:

```
[compactions]
_default = disabled
```

**Comment by rvanzon** [comment] 2017-09-27 17:19
@wohali thanks!

**Comment by wohali** [comment] 2017-09-29 06:34
Duplicate of #732.

**Closed by wohali** 2017-09-29 06:34 UTC

**Comment by navneet21sharma** [comment] 2018-05-12 16:09
I am having CouchDB 2.1.1  for mac and having same issue. When I start couchDB then it start opening new tab with address http://127.0.0.1:5984/_utils/ and refused to connect.  It continue to open until I force quit it. I tried to do according to your reply but Didn't find local.ini file. Please let me know the path of this file for mac 
Please find crash log file 
[CouchDB2.log](https://github.com/apache/couchdb/files/1997744/CouchDB2.log)

**Comment by navneet21sharma** [comment] 2018-05-12 16:53
oh, I was not able to read that issue from logs. Thanks for your reply, I tried to find local.ini file but didn't find the path of this file. Can you please help me to find this file so that I can change it to 0.0.0.0

**Comment by navneet21sharma** [comment] 2018-05-12 17:11
I found it under cd /Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/local.ini 
It was having 127.0.0.1 under chttpd . Then again I checked and got this log. It is still showing the same {{shutdown,{failed_to_start_child,chttpd,invalid_bind_address}} issue. 
[CouchDB2.log](https://github.com/apache/couchdb/files/1997780/CouchDB2.log)
