### ISSUE TITLE
Broken unicode in CouchDB 3.0.0

### ISSUE THREAD

**Issue by kimaiavd** [apache/couchdb#2779] opened 2020-04-12 13:16 UTC
## Description

After upgrading to CouchDB 3 we had a big problem with JS query server that now incorrectly works with unicode characters.

## Steps to Reproduce

Create view with following map function:

`function (doc) { log(doc.string_field.length); }`

Put document with field `string_field` with any unicode characters. We're have text fields with Hebrew and Russian. Now you can see in console incorrect string length. Thus `substring` and `slice` also don't work.

For example:

`{"string_field": "мама мыла раму"}`

## Expected Behaviour

Correct behaviour of `length`, `substring` and `slice`.

## Your Environment

CouchDB 3.0 in single node mode or CouchDB 3.0 in cluster mode with 3 nodes. Installed from official docker image on 64bit host system.

* CouchDB version used: CouchDB 3.0, git_sha: `03a77db6c `
* Operating system and version: Official docker image - `couchdb:3`

**Comment by wohali** [comment] 2020-04-12 18:48
Duplicate of #2756 . Thanks for the additional background.

**Closed by wohali** 2020-04-12 18:48 UTC
Labels: bug, needs-triage
