### ISSUE TITLE
Flexible replicator client auth + session support

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#1153] opened 2018-02-07 18:52 UTC
Even though session / cookie based authentication has been around for years, replicator only knows how to use basic authentication. Let's teach it to use session based authentication to get better performance and flexibility. 

Using basic authentication means sending username and password credentials with every request. It certainly is simple and with a fast password hashing algorithm like SHA1 it's not too bad performance-wise. However when the newer PBKDF2 password hashing is used, especially with a larger work factor, which by design slows down authentication speed, performance can start to suffer. 

### Proposal

Implement a simple pluggable framework for replication clients. Make basic auth, currently OAuth 1.0 and the new session support act as plugins. This allows extending it in the future adding OAuth 2.0 or a customer-specific scheme without too much work. Also if OAuth 1.0 is not used very much when it is moved to a separate plugin it is easier to deprecated or make it disable by default, then eventually removing it.

### Specifics

A list of replicator client authentication handler modules is specified in the config file. This list is ordered and defines a precedence. For example it could look like:

```
[replicator]
client_auth_modules = [replicator_client_auth_oauth, replicator_client_auth_session]
```
 An instance of a client authentication context is created for both the source and target endpoints. When a replication job starts, it uses the per-endpoint specific information (headers, url, connection timeouts), config options and possibly the presence of  specific endpoints like say _session to pick an active authentication handler.

Then, before each request to an endpoint, authentication handler is allowed to update the request headers with authentication info. During update the handler might fetch and refresh a token or cookie and add then cookie to the header list.

If the request fails with a 401, authentication handler is notified. Internally it might decide to update the cookie and return a "retry" to signal that the request is safe to retry or it could fail and signal that the 401 failure should propagate, and possibly crash the replication job.

### Erlang API

This is the proposed interface to the `couch_replicator_auth` module:

```
initialize(#httpdb{}) -> {ok, #httpdb{}} | {error, Error}

update_headers(#httpdb{}, Headers) -> {ok, UpdatedHeaders} | {error, Error}

handle_response(#httpdb{}, ResponseCode, ResponseMessage) -> ok | retry | {error, Error}

cleanup(#httpdb{}) -> #httpdb{}
```

`initialize/1` will be called after the connection worker is spawned but before the first request is made:
https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_api_wrap.erl#L74

`update_headers/2` and `handle_response/3` will be called in httpc module before and after the request: https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_httpc.erl#L89

`#httpd{}` is the parsed endpoint information. It will contain credentials, headers, URLs and possibly other bits: https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_api_wrap.hrl 

`#httpdb{}` record will be updated to have a few extra fields. It will store the opaque context retrieved from the client auth plugin initialize/1 call. OAuth will be moved to a plugin.

`cleanup/1` function will be called after the session is no longer needed. It allows the active plugin to stop any processes or do other necessary cleanup. The return is an updated `#httpdb{}`  record with the client_auth_context set to nil

**Comment by wohali** [comment] 2018-02-07 19:38
+1. Note that this might reduce or eliminate the need to implement #959 as well.

@janl also wants this, I'm pretty sure.

**Comment by nickva** [comment] 2018-02-07 19:39
@wohali Good point! Even more reason to have it

**Comment by wohali** [comment] 2018-02-07 19:41
Just re-read your proposal.

OAuth 1.0 support was removed from CouchDB in 2.1.0, see https://github.com/apache/couchdb/commit/34b803a35531f305e05080c35c3e9af9e3b9dbf2 .

The stubs for OAuth support were left in the replicator code in the hopes we'd move towards a future implementation of something better. I do know that @rnewson was looking at JWT-like token support, and there is of course the current proxy auth implementation that we recommend as a first choice for people who don't like the current options.

Finally, be aware of this issue #844 in which there is at least one request for the ability to "revoke" a session token. By design this isn't possible right now. Just something to consider as we look at new implementation ideas.

**Comment by nickva** [comment] 2018-02-07 19:55
Hmm wonder what we should do about OAuth 1.0 support in the replicator then.  Really not sure how much it is used.  Maybe there is someone is still using it to replicate to / from a CouchDB instance which supports it (to migrate data) or with some service. Or using it together with proxy auth and their proxy handles OAuth 1.0. If the community feels like it is not needed could remove. Shoving all those bits in a plugin module would at least make it easier to disable.

Thanks for pointing out #844. Yeah that would good to consider. If we can return an unambiguous reply that the token has been revoked we can even re-use the new replication feature and mark that replication as "failed" so the job doesn't keep retrying.

**Comment by wohali** [comment] 2018-02-07 20:02
I'm fairly certain that no one is actively using OAuth 1.0 support in 2.x except to connect to a 1.x cluster that has OAuth 1.0 activated. I doubt very much that anyone is putting an OAuth 1.0-enabled proxy in front of CouchDB 2.x, but who knows?

The issue, of course, is that session tokens can't be revoked right now. :)

**Comment by nickva** [comment] 2018-02-07 23:31
Well it looks like when we remove OAuth 1.0 we removed the `oauth` app which replicator would need to use OAuth. At this point we might as well remove it the whole thing it seems.

**Comment by janl** [comment] 2018-02-08 15:16
I’m very +1 on this. Just a few notes.

Implementation idea: I like the adapter implementation plan.

OAuth 1 : as seems to be consensus here already, nuke to appropriate orbit.

> A list of replicator client authentication handler modules is specified in the config file

I know this is how we’ve done this in the past, and that this makes it relatively easy for Cloudant to customise things, but I think we want to move away from having too many code-level config items. The ini files are unwieldy as is, and we should think about moving this to a separate, source-level config file (like we’ve done for the stats cfg).

```
update_headers(#httpdb{}, Headers) -> {ok, UpdatedHeaders} | {error, Error}

handle_response(#httpdb{}, ResponseCode, ResponseMessage) -> ok | retry | {error, Error}
```

I’m just wondering about symmetry here, could `update_headers` also be `handle_request`? Just seems more what the intent of this function is, rather than an implementation detail. // imagine an auth format that messes with the body (not that that one should have such a format, bear with me) as well as the headers, that’d be awkward to finagle into this signature. // just a question :)

**Comment by nickva** [comment] 2018-02-08 16:56
Thank for the comments, @janl 

In case of the config ini / cfg files. I think there won't be many more config settings besides the plugin list. And even there it would not be the full on mfa format (like in the server side auth plugins list), just a list of modules separated commas.

Ini files are not perfect, but I don't hate them, they allow overrides, loading from a *.d directory, stuff is put into an ets table optimized for concurrent reads,  we have a documentation section for it etc. The source config for stats work well because they are relatively static (change with code), it's more structured data, and there are a ton of them (that would bloat the ini file if it were there).

With `update_headers` initially I started with something that took the whole request, body and headers, however thinking about it seemed the API was too broad. All use cases I could think of we only update headers, so restricted it back down.

The `handle_response` is more broad because various plugins might want to inspect error response to make decisions how to proceed, say get a new token or has it be been revoked and it will never be valid again. So Basically the API is inherently not symmetric. The more specific name  is also helpful when reading the the section in the code where it is called, as it explain what it will do, as opposed to passing in the whole request body and wondering how much was really modified or what it does behind the scenes.

**Comment by janl** [comment] 2018-02-08 20:37
Thanks for the explanation!

**Closed** 2018-03-05 18:29 UTC
Labels: discussion, enhancement
