### ISSUE TITLE
_bulk_docs with new_edits is false should not return empty array.

### ISSUE THREAD

**Issue by snowyu** [apache/couchdb#2226] opened 2019-10-03 13:06 UTC
## Description

Based on _bulk_docs endpoint documentation, there is required to id field in response. But the current operation with new_edits is always return an empty array.

## Steps to Reproduce

```js
Request
POST _bulk_docs
{
  "new_edits": false,
  "docs": [
      {
         "_id": "test",
         "_rev": "1-init",
       }
  ]
}
Response
[]
```

## Expected Behaviour

```js
Response
[
    {
        "ok": true,
        "id": "test",
        "rev":" 1-init"
    },
 
```

## Your Environment

* CouchDB Version 2.3.1
* Ubuntu 19.04

**Comment by meten-natuurlijk** [comment] 2020-07-10 06:29
I am seeing the exact same behaviour on CouchDB 3.1.0

**Comment by nickva** [comment] 2021-11-04 18:17
Empty array is currently the expected response for _bulk_docs with `new_edits:false` it's not a bug.

In general, there is no expectation that the behavior of `new_edits:false` API would be the same as for `new_edits:true`. If we were to design the API from scratch, we'd probably make these two separate API endpoints even. 

Now, we could enhance `new_edits:false` to return something new, say, return only the branches which were extended but that should be a wider mailing list discussion perhaps.

Closing the issue for now.

**Closed by nickva** 2021-11-04 18:17 UTC
Labels: bug, patches-welcome

**Comment by snowyu** [comment] 2021-11-07 01:38
doesnt matter. I give up couchdb now.
